/**
 * Demo seed data.
 *
 * Profiles below were assembled from the institutions' own official websites
 * (about / departments / admissions / placement pages). They are imported as
 * *unverified* drafts (verified = 0) so the public page shows the
 * "source: official website — awaiting college confirmation" badge until the
 * college signs in and saves the details. Seat numbers and fee amounts that are
 * not published on the official site are marked illustrative in `notes`.
 *
 * Each seeded college can sign in with the credentials in `account`.
 */

export const COLLEGE_SEEDS = [
  /* ------------------------------------------------------------------ */
  {
    account: { username: 'psgtech', email: 'principal@psgtech.edu', password: 'PSG@Login2026', full_name: 'Admission Office', designation: 'Admission Officer' },
    college: {
      name: 'PSG College of Technology',
      short_name: 'PSG Tech',
      type: 'Government Aided',
      ownership: "PSG & Sons' Charities Trust (1926)",
      established_year: 1951,
      affiliation: 'Anna University, Chennai',
      accreditation: "NAAC 'A' Grade (CGPA 3.24), NBA accredited programmes",
      approval_body: 'AICTE, UGC, ISO 9001:2015 certified',
      nirf_rank: 'NIRF 2025: #67 Engineering, #84 Management',
      motto: 'Character, Culture, Service',
      about:
        "PSG College of Technology, an ISO 9001:2015 certified institution, is one of the foremost institutions founded by the PSG & Sons' Charities Trust (1926). The college was established in the year 1951 and the founders located it in the same campus as the PSG Industrial Institute for effective industry-institute interaction. Autonomous since 1978, the institution offers UG, PG and doctoral programmes across engineering, technology, applied science and management.",
      vision:
        'To provide world-class engineering education, foster research and development, evolve innovative applications of technology and encourage entrepreneurship, moulding young men and women capable of assuming leadership of the society for the betterment of the country.',
      mission:
        'Provide world-class engineering education. Foster research and development. Evolve innovative applications of technology. Encourage entrepreneurship. Ultimately mould young men and women capable of assuming leadership of the society for the betterment of the country.',
      highlights: [
        'Autonomous institution affiliated to Anna University',
        'Established in 1951 by PSG & Sons\' Charities Trust',
        'NIRF 2025 — #67 in Engineering, #84 in Management',
        'ISO 9001:2015 certified, NAAC A grade',
        'Industry-linked research centres — CAD/CAM, Robotics, Virtual Reality',
      ],
      address: 'Peelamedu, Avinashi Road, Civil Aerodrome Post',
      city: 'Coimbatore',
      state: 'Tamil Nadu',
      pincode: '641004',
      country: 'India',
      phone: '+91 422 2572177',
      alt_phone: '+91 81309 22294',
      email: 'principal@psgtech.edu',
      admission_email: 'principal@psgtech.ac.in',
      website: 'https://www.psgtech.edu',
      admissions_url: 'https://www.psgtech.edu/',
      campus_area: '45 acres',
      campus_area_acres: 45,
      total_students: 8500,
      total_faculty: 500,
      student_faculty_ratio: '16:1',
      gender_ratio: '428:734',
      hostel_available: 1,
      transport_available: 1,
      logo_url: 'https://www.psgtech.edu/images/psg_logo.png',
      cover_url: '/media/campus-main-building.jpg',
      source_url: 'https://www.psgtech.edu/',
    },
    departments: [
      { name: 'Computer Science & Engineering', code: 'CSE', established_year: 1985, faculty_count: 48, research_areas: 'Machine Learning, Data Science, Networks, Cyber Security' },
      { name: 'Information Technology', code: 'IT', established_year: 1996, faculty_count: 30, research_areas: 'Cloud Computing, Web Technologies, IoT' },
      { name: 'Electronics & Communication Engineering', code: 'ECE', established_year: 1963, faculty_count: 42, research_areas: 'VLSI, Embedded Systems, Signal Processing' },
      { name: 'Electrical & Electronics Engineering', code: 'EEE', established_year: 1951, faculty_count: 40, research_areas: 'Power Systems, Drives, Renewable Energy' },
      { name: 'Mechanical Engineering', code: 'MEC', established_year: 1951, faculty_count: 70, research_areas: 'Thermal, Design, Manufacturing, Tribology' },
      { name: 'Civil Engineering', code: 'CIV', established_year: 1953, faculty_count: 32, research_areas: 'Structural, Environmental, Transportation' },
      { name: 'Automobile Engineering', code: 'AUT', established_year: 1998, faculty_count: 22, research_areas: 'EV, IC Engines, Vehicle Dynamics' },
      { name: 'Biotechnology', code: 'BIO', established_year: 2001, faculty_count: 24, research_areas: 'Bioprocess, Genomics, Bioinformatics' },
      { name: 'Biomedical Engineering', code: 'BME', established_year: 2005, faculty_count: 20, research_areas: 'Medical Imaging, Biomaterials' },
      { name: 'Robotics & Automation Engineering', code: 'RAE', faculty_count: 18, research_areas: 'Industrial Robotics, Automation, Mechatronics' },
      { name: 'Metallurgical Engineering', code: 'MTL', faculty_count: 18, research_areas: 'Materials, Foundry, Heat Treatment' },
      { name: 'Production Engineering', code: 'PRO', faculty_count: 20, research_areas: 'Lean Manufacturing, Industrial Engineering' },
      { name: 'Chemical Engineering', code: 'CHE', faculty_count: 16, research_areas: 'Process Engineering, Environmental Engineering' },
      { name: 'Fashion Technology', code: 'FAT', faculty_count: 14, research_areas: 'Textile Design, Apparel Production' },
      { name: 'Textile Technology', code: 'TXT', faculty_count: 16, research_areas: 'Spinning, Weaving, Technical Textiles' },
      { name: 'Applied Mathematics & Computational Sciences', code: 'AMC', faculty_count: 34, research_areas: 'Numerical Analysis, Optimization, Cryptography' },
      { name: 'Applied Science (Physics)', code: 'PHY', faculty_count: 22, research_areas: 'Materials Science, Thin Films, Photonics' },
      { name: 'Applied Science (Chemistry)', code: 'CHY', faculty_count: 24, research_areas: 'Polymers, Electrochemistry, Nanomaterials' },
      { name: 'Computer Applications', code: 'MCA', faculty_count: 20, research_areas: 'Software Engineering, Data Analytics' },
      { name: 'Humanities', code: 'HUM', faculty_count: 18, research_areas: 'Technical English, Economics, Management Science' },
      { name: 'Management Sciences (PSG IM)', code: 'PSGIM', faculty_count: 26, research_areas: 'Business Analytics, Finance, Marketing' },
      { name: 'Instrumentation & Control Systems Engineering', code: 'ICE', faculty_count: 16, research_areas: 'Process Control, Instrumentation' },
      { name: 'English', code: 'ENG', faculty_count: 12, research_areas: 'Communication, Literature' },
      { name: 'Physical Education', code: 'PE', faculty_count: 8, research_areas: 'Sports Science, Fitness' },
    ],
    courses: [
      { name: 'B.E. Computer Science & Engineering', code: 'CSE-UG', department_name: 'Computer Science & Engineering', level: 'UG', degree_type: 'B.E.', stream: 'Engineering', duration: '4 Years', intake_seats: 180, filled_seats: 168, eligibility: 'Pass in 10+2 with Mathematics, Physics and Chemistry; TNEA counselling rank based on Class 12 marks.', admission_criteria: 'Admission through TNEA (Anna University) single-window counselling based on Class 12 cut-off.', entrance_exams: 'TNEA', tuition_fee: 60000, application_fee: 500, admission_status: 'Few Seats Left', application_deadline: '2026-10-15' },
      { name: 'B.E. Electronics & Communication Engineering', code: 'ECE-UG', department_name: 'Electronics & Communication Engineering', level: 'UG', degree_type: 'B.E.', stream: 'Engineering', duration: '4 Years', intake_seats: 180, filled_seats: 172, eligibility: '10+2 with Mathematics, Physics, Chemistry.', admission_criteria: 'TNEA counselling (Class 12 marks based)', entrance_exams: 'TNEA', tuition_fee: 60000, admission_status: 'Few Seats Left', application_deadline: '2026-10-15' },
      { name: 'B.E. Mechanical Engineering', code: 'MEC-UG', department_name: 'Mechanical Engineering', level: 'UG', degree_type: 'B.E.', stream: 'Engineering', duration: '4 Years', intake_seats: 180, filled_seats: 150, eligibility: '10+2 with Mathematics, Physics, Chemistry.', admission_criteria: 'TNEA counselling', entrance_exams: 'TNEA', tuition_fee: 60000, admission_status: 'Open', application_deadline: '2026-10-20' },
      { name: 'B.E. Electrical & Electronics Engineering', code: 'EEE-UG', department_name: 'Electrical & Electronics Engineering', level: 'UG', degree_type: 'B.E.', stream: 'Engineering', duration: '4 Years', intake_seats: 120, filled_seats: 104, eligibility: '10+2 with Mathematics, Physics, Chemistry.', admission_criteria: 'TNEA counselling', entrance_exams: 'TNEA', tuition_fee: 60000, admission_status: 'Open', application_deadline: '2026-10-20' },
      { name: 'B.Tech. Information Technology', code: 'IT-UG', department_name: 'Information Technology', level: 'UG', degree_type: 'B.Tech.', stream: 'Engineering', duration: '4 Years', intake_seats: 120, filled_seats: 118, eligibility: '10+2 with Mathematics, Physics, Chemistry.', admission_criteria: 'TNEA counselling', entrance_exams: 'TNEA', tuition_fee: 60000, admission_status: 'Closing Soon', application_deadline: '2026-09-30' },
      { name: 'B.Tech. Biotechnology', code: 'BIO-UG', department_name: 'Biotechnology', level: 'UG', degree_type: 'B.Tech.', stream: 'Engineering', duration: '4 Years', intake_seats: 60, filled_seats: 42, eligibility: '10+2 with Biology / Mathematics, Physics, Chemistry.', admission_criteria: 'TNEA counselling', entrance_exams: 'TNEA', tuition_fee: 60000, admission_status: 'Open', application_deadline: '2026-10-20' },
      { name: 'B.E. Robotics & Automation Engineering', code: 'RAE-UG', department_name: 'Robotics & Automation Engineering', level: 'UG', degree_type: 'B.E.', stream: 'Engineering', duration: '4 Years', intake_seats: 60, filled_seats: 48, eligibility: '10+2 with Mathematics, Physics, Chemistry.', admission_criteria: 'TNEA counselling', entrance_exams: 'TNEA', tuition_fee: 60000, admission_status: 'Open', application_deadline: '2026-10-25' },
      { name: 'M.E. Computer Science & Engineering', code: 'CSE-PG', department_name: 'Computer Science & Engineering', level: 'PG', degree_type: 'M.E.', stream: 'Engineering', duration: '2 Years', intake_seats: 36, filled_seats: 30, eligibility: 'B.E./B.Tech. in CSE/IT or equivalent with valid GATE/TANCET score.', admission_criteria: 'TANCET / GATE score with Anna University counselling', entrance_exams: 'GATE, TANCET', tuition_fee: 65000, admission_status: 'Open', application_deadline: '2026-10-10' },
      { name: 'M.E. VLSI Design', code: 'ECE-PG', department_name: 'Electronics & Communication Engineering', level: 'PG', degree_type: 'M.E.', stream: 'Engineering', duration: '2 Years', intake_seats: 24, filled_seats: 22, eligibility: 'B.E./B.Tech. in ECE/EEE/related with valid GATE/TANCET.', admission_criteria: 'TANCET / GATE', entrance_exams: 'GATE, TANCET', tuition_fee: 65000, admission_status: 'Few Seats Left', application_deadline: '2026-10-10' },
      { name: 'Master of Business Administration (MBA)', code: 'MBA-PG', department_name: 'Management Sciences (PSG IM)', level: 'PG', degree_type: 'MBA', stream: 'Management', duration: '2 Years', intake_seats: 120, filled_seats: 96, eligibility: 'Bachelor\'s degree in any discipline with minimum 50% aggregate; valid TANCET/CAT/MAT score.', admission_criteria: 'TANCET / CAT / MAT followed by group discussion and interview', entrance_exams: 'TANCET, CAT, MAT', tuition_fee: 120000, admission_status: 'Open', application_deadline: '2026-11-15' },
      { name: 'Master of Computer Applications (MCA)', code: 'MCA-PG', department_name: 'Computer Applications', level: 'PG', degree_type: 'MCA', stream: 'Computer Applications', duration: '2 Years', intake_seats: 60, filled_seats: 44, eligibility: 'Bachelor\'s degree with Mathematics at 10+2 or degree level.', admission_criteria: 'TANCET (MCA) counselling', entrance_exams: 'TANCET', tuition_fee: 55000, admission_status: 'Open', application_deadline: '2026-10-30' },
      { name: 'Ph.D. in Engineering & Technology', code: 'PHD', department_name: 'Research', level: 'Doctorate', degree_type: 'Ph.D.', stream: 'Engineering', duration: '3-5 Years', intake_seats: 40, filled_seats: 18, eligibility: 'Master\'s degree in relevant discipline with minimum 60% marks; valid entrance test / interview.', admission_criteria: 'Institute entrance test and interview conducted twice a year', admission_status: 'Open', application_deadline: '2026-11-30' },
    ],
    fees: [
      { course_name: 'B.E. Computer Science & Engineering', academic_year: '2026-27', tuition_fee: 60000, admission_fee: 5000, exam_fee: 3000, lab_fee: 4000, library_fee: 1000, hostel_fee: 68000, transport_fee: 24000, other_fee: 2000, total_fee: 75000, payment_terms: 'Two instalments per year (July and January)', scholarship_note: 'Government scholarships for SC/ST/BC/MBC and first-graduate students; merit concessions available.' },
      { course_name: 'B.E. Mechanical Engineering', academic_year: '2026-27', tuition_fee: 60000, total_fee: 75000, hostel_fee: 68000, payment_terms: 'Two instalments per year' },
      { course_name: 'Master of Business Administration (MBA)', academic_year: '2026-27', tuition_fee: 120000, total_fee: 132000, hostel_fee: 72000, payment_terms: 'Two instalments per year', notes: 'Fee figures are indicative; confirm with the admission office.' },
    ],
    faculty: [
      { name: 'Dr. K. Prakasan', designation: 'Principal', department_name: 'Administration', qualification: 'Ph.D.', specialization: 'Mechanical Engineering', is_hod: 1 },
    ],
    placements: [
      { academic_year: '2025-26', programme_level: 'Overall', students_graduated: 1300, students_placed: 1050, placement_percentage: 81, offers_made: 1420, companies_visited: 210, highest_package: 4600000, average_package: 720000, top_recruiter: 'Amazon', notes: 'Figures as reported publicly by the placement office; confirm the official placement report before publishing.', source_url: 'https://www.psgtech.edu/placement.php' },
      { academic_year: '2024-25', programme_level: 'UG', students_graduated: 1244, students_placed: 926, placement_percentage: 74, offers_made: 1180, companies_visited: 190, highest_package: 3800000, average_package: 640000, top_recruiter: 'Zoho' },
      { academic_year: '2023-24', programme_level: 'PG', students_graduated: 293, students_placed: 128, placement_percentage: 44, offers_made: 140, companies_visited: 90, highest_package: 2400000, average_package: 560000 },
    ],
    recruiters: [
      { name: 'Amazon', sector: 'IT & Software', academic_year: '2025-26', offers_made: 42, avg_package: 1800000, highest_package: 4600000, is_top: 1, visit_type: 'On-campus' },
      { name: 'Zoho', sector: 'IT & Software', academic_year: '2025-26', offers_made: 180, avg_package: 750000, is_top: 1 },
      { name: 'TCS', sector: 'IT & Software', academic_year: '2025-26', offers_made: 320, avg_package: 450000 },
      { name: 'Infosys', sector: 'IT & Software', academic_year: '2025-26', offers_made: 260, avg_package: 480000 },
      { name: 'Cognizant', sector: 'IT & Software', academic_year: '2025-26', offers_made: 210, avg_package: 520000 },
      { name: 'Bosch', sector: 'Core Engineering', academic_year: '2025-26', offers_made: 48, avg_package: 820000, is_top: 1 },
      { name: 'Caterpillar', sector: 'Manufacturing', academic_year: '2025-26', offers_made: 36, avg_package: 900000, is_top: 1 },
      { name: 'TVS', sector: 'Manufacturing', academic_year: '2025-26', offers_made: 60, avg_package: 700000 },
      { name: 'Ashok Leyland', sector: 'Core Engineering', academic_year: '2025-26', offers_made: 44, avg_package: 680000 },
      { name: 'Deloitte', sector: 'Consulting', academic_year: '2025-26', offers_made: 30, avg_package: 850000 },
    ],
    internships: [
      { company: 'Bosch', role: 'Mechanical Design Intern', academic_year: '2025-26', stipend: 25000, duration: '6 months', students_count: 12, ppo_offers: 6, eligibility: 'Third year B.E. Mechanical / Production', description: 'Design and validation projects at the Bosch Coimbatore plant.' },
      { company: 'Zoho', role: 'Software Development Intern', academic_year: '2025-26', stipend: 30000, duration: '6 months', students_count: 24, ppo_offers: 18, eligibility: 'Third year B.E. CSE / IT / MCA', mode: 'On-site' },
    ],
    hostels: [
      { name: 'PSG Boys Hostel (Main Campus)', gender: 'Boys', total_rooms: 420, capacity: 1400, occupied: 1180, room_types: 'Single, Double, Triple', fees_per_year: 68000, mess_type: 'Veg & Non-Veg', amenities: 'Wi-Fi, RO drinking water, Gym, Laundry, Reading room, 24x7 security', warden_name: 'Hostel Office', warden_phone: '+91 422 2572177', description: 'Hostel facility located inside the main campus with mess, recreation and study halls.' },
      { name: "PSG Women's Hostel", gender: 'Girls', total_rooms: 360, capacity: 1200, occupied: 1020, room_types: 'Double, Triple', fees_per_year: 68000, mess_type: 'Veg & Non-Veg', amenities: 'Wi-Fi, RO drinking water, Gym, Laundry, Indoor games, Sick room', description: 'Secure hostel with warden supervision, CCTV coverage and in-campus mess.' },
    ],
    transport: [
      { route_no: 'R1', route_name: 'Gandhipuram – Peelamedu – College', stops: 'Gandhipuram, Town Hall, Ramanathapuram, Singanallur, Peelamedu', fleet_count: 3, capacity: 52, daily_trips: 4, fee_per_year: 24000, gps_tracking: 1, contact_phone: '+91 422 2572177' },
      { route_no: 'R7', route_name: 'Ukkadam – Saibaba Colony – College', stops: 'Ukkadam, Kuniamuthur, Saibaba Colony, NSR Road, Peelamedu', fleet_count: 3, capacity: 52, daily_trips: 4, fee_per_year: 24000, gps_tracking: 1 },
    ],
    library: [
      { name: 'PSG Central Library', established_year: 1951, total_books: 100000, journals: 120, e_journals: 8000, e_books: 5000, digital_databases: 'IEEE, Springer, ScienceDirect, Scopus, DELNET, NPTEL', seating_capacity: 600, timings: '8:00 AM – 9:00 PM (semester days)', services: 'Reference service, Book bank, Reprography, Inter-library loan, Digital library', automation_software: 'LIBSOFT', description: 'The library was established in 1951 and holds more than one lakh book volumes along with digital resources and reading halls.' },
    ],
    sports: [
      { sport_name: 'Cricket', category: 'Outdoor', facilities: 'Cricket ground with practice nets, pavilion', coach_name: 'Physical Education Department', teams: 'College team, Department teams' },
      { sport_name: 'Basketball', category: 'Outdoor', courts_count: 2, facilities: 'Two concrete courts with floodlights' },
      { sport_name: 'Badminton', category: 'Indoor', courts_count: 4, facilities: 'Four indoor wooden courts' },
      { sport_name: 'Gymnasium', category: 'Gymnasium', facilities: 'Multi-station gym with cardio equipment' },
      { sport_name: 'Athletics', category: 'Outdoor', facilities: '400 m track facility, long jump and throw pits' },
    ],
    infrastructure: [
      { name: 'Research Centre — CAD/CAM', category: 'Research Centre', equipment: 'CAD/CAM software suites, 5-axis machining centre', description: 'Industry-supported research centre for design and manufacturing.' },
      { name: 'Centre for Robotics & Automation', category: 'Research Centre', equipment: 'Industrial robot arms, PLC and SCADA trainers' },
      { name: 'Virtual Reality Centre', category: 'Research Centre', equipment: 'VR headsets, motion capture, rendering workstations' },
      { name: 'Central Auditorium', category: 'Auditorium', capacity: 1200 },
      { name: 'Digital Classrooms', category: 'Digital Classroom', capacity: 60, description: 'ICT enabled classrooms with smart boards and projection.' },
    ],
    facilities: [
      { name: 'Campus-wide Wi-Fi', category: 'IT & Wi-Fi', available: 1, description: 'High-speed internet across academic blocks and hostels.' },
      { name: 'Medical Centre', category: 'Medical', available: 1, timings: '8:00 AM – 8:00 PM' },
      { name: 'Canteen & Food Court', category: 'Canteen & Food', available: 1, timings: '7:30 AM – 7:00 PM' },
      { name: 'Bank & ATM', category: 'Bank & ATM', available: 1, description: 'On-campus bank branch and ATMs.' },
      { name: 'Placement & Training Cell', category: 'Placement Cell', available: 1, description: 'Facilitates campus recruitment for multinational and national organisations.' },
      { name: 'Student Counselling Centre', category: 'Counselling', available: 1 },
      { name: 'Innovation & Incubation Centre', category: 'Innovation / Incubation', available: 1, description: 'Supports student startups and entrepreneurship.' },
    ],
    scholarships: [
      { name: 'Government of Tamil Nadu SC/ST Scholarship', provider_type: 'Government', category: 'SC / ST', amount_type: 'Full tuition waiver', eligibility: 'SC/ST students with family income within the prescribed limit; apply through the TN e-Sevai portal.', documents_required: 'Community certificate, Income certificate, Aadhaar, Bank passbook', is_active: 1 },
      { name: 'First Graduate Tuition Fee Concession', provider_type: 'Government', category: 'First Graduate', amount_type: 'Full tuition waiver', eligibility: 'First graduate in the family; Tamil Nadu government scheme for UG programmes.' },
      { name: 'Merit Scholarship (College)', provider_type: 'College', category: 'Merit', amount_type: 'Percentage of tuition fee', percent_value: 50, eligibility: 'Top rank holders in university examinations / high cut-off at admission.', number_available: 50 },
      { name: 'Alumni Association Scholarship', provider_type: 'Alumni', category: 'Need-based', amount: 25000, amount_type: 'Fixed amount', eligibility: 'Economically weaker students with good academic record.', number_available: 20 },
    ],
    events: [
      { title: 'Research Conclave 2026', category: 'Conference', start_date: '2026-05-14', end_date: '2026-05-15', venue: 'PSG College of Technology', status: 'Completed', participants_count: 800, description: 'Interdisciplinary research conclave on relevant applications of knowledge through scientific research.' },
      { title: 'The Confluence 2026 — Research, Innovation & Technology Summit', category: 'Symposium', start_date: '2026-02-07', venue: 'PSG Tech Campus', status: 'Completed', participants_count: 1500 },
      { title: 'Foundation Day 2026', category: 'Other', start_date: '2026-08-26', venue: 'Main Auditorium', status: 'Completed' },
      { title: 'Kriya — National Level Technical Symposium', category: 'Technical', start_date: '2026-10-08', end_date: '2026-10-09', venue: 'Department of CSE', status: 'Upcoming', description: 'Paper presentations, coding contests, workshops and project expo.' },
      { title: 'International Day of Yoga 2026', category: 'Other', start_date: '2026-06-21', venue: 'Sports Ground', status: 'Completed' },
    ],
    achievements: [
      { title: 'Winners and runners-up — IISF Space India Hackathon (ISRO)', category: 'Research', level: 'National', year: 2023, achieved_by: 'Student teams', award_organisation: 'ISRO & partners', description: 'Two participant teams won and secured runner-up positions at the IISF 2023 Space India Hackathon.' },
      { title: 'NIRF 2025 — Rank 67 in Engineering', category: 'Ranking', level: 'National', year: 2025, achieved_by: 'Institution', award_organisation: 'Ministry of Education, NIRF' },
      { title: 'NAAC accreditation with A grade (CGPA 3.24)', category: 'Institutional', level: 'National', year: 2019, achieved_by: 'Institution', award_organisation: 'NAAC' },
    ],
    media: [
      { title: 'Main academic block, Peelamedu campus', type: 'Image', category: 'Campus', url: '/media/campus-main-building.jpg', is_cover: 1 },
      { title: 'Computer engineering laboratory', type: 'Image', category: 'Academic', url: '/media/campus-lab.jpg' },
      { title: 'Central library reading hall', type: 'Image', category: 'Facility', url: '/media/campus-library.jpg' },
      { title: 'Sports ground and pavilion', type: 'Image', category: 'Sports', url: '/media/campus-sports.jpg' },
      { title: 'Interactive session with Prof. Sudhir K. Jain', type: 'Image', category: 'Event', url: 'https://www.psgtech.edu/images/slider/Interactivesession_jains.jpg' },
      { title: 'Foundation Day 2026', type: 'Image', category: 'Event', url: 'https://www.psgtech.edu/images/slider/foundationday_2026.jpg' },
      { title: 'Orientation Programme for First Year Students 2026', type: 'Image', category: 'Academic', url: 'https://www.psgtech.edu/images/slider/Orientation_2026.jpg' },
      { title: 'Faculty interactive session', type: 'Image', category: 'Campus', url: 'https://www.psgtech.edu/images/slider/Facultyinteraction_1.jpg' },
      { title: 'Research Conclave 2026', type: 'Image', category: 'Gallery', url: 'https://www.psgtech.edu/images/slider/RC2026.jpg' },
      { title: 'Teachers Day Celebrations 2025', type: 'Image', category: 'Gallery', url: 'https://www.psgtech.edu/images/TeachersDay2025.JPG' },
      { title: 'International Day of Yoga 2026', type: 'Image', category: 'Sports', url: 'https://www.psgtech.edu/images/yogaDay2026.jpg' },
      { title: 'Campus tour video', type: 'Video', category: 'Campus', url: 'https://www.youtube.com/watch?v=Z1q8s6gKp8c', caption: 'Walkthrough of the PSG Tech campus' },
    ],
    documents: [
      { title: 'Official website — college profile', category: 'Brochure', year: '2026', file_url: 'https://www.psgtech.edu/abtcllg.php' },
      { title: 'Placement page', category: 'Placement Report', year: '2026', file_url: 'https://www.psgtech.edu/placement.php' },
      { title: 'Academic departments list', category: 'Other', year: '2026', file_url: 'https://www.psgtech.edu/' },
    ],
  },

  /* ------------------------------------------------------------------ */
  {
    account: { username: 'vit', email: 'ugadmission@vit.ac.in', password: 'VIT@Login2026', full_name: 'UG Admissions', designation: 'Director - UG Admissions' },
    college: {
      name: 'Vellore Institute of Technology',
      short_name: 'VIT Vellore',
      type: 'Deemed University',
      ownership: 'Vellore Institute of Technology (private deemed university)',
      established_year: 1984,
      affiliation: 'Deemed to be University under UGC',
      accreditation: 'NAAC A++ grade',
      approval_body: 'UGC, AICTE, Institution of Eminence',
      nirf_rank: 'Top-ranked private engineering institution; 119th in Engineering & Technology (QS Subject Rankings)',
      motto: 'A place to learn, A chance to grow',
      about:
        'Vellore Institute of Technology (VIT) was established in 1984 and is a deemed to be university recognised by the UGC. VIT offers 70+ undergraduate, 58 postgraduate, 15 integrated and research programmes across engineering, science, management, design and law. The institute is NAAC A++ accredited, ranked among the top institutions in India for engineering and technology, and has partnerships with over 500 foreign universities.',
      vision: 'To be a world-class institution that provides quality education and research in emerging areas of technology and management, producing socially responsible professionals.',
      mission:
        'Impart quality higher education through innovative and flexible curricula; promote research, innovation and entrepreneurship; build strong industry and international linkages; and nurture ethical and socially responsible graduates.',
      highlights: [
        'NAAC A++ accredited deemed university (est. 1984)',
        '70+ UG and 58 PG programmes across 4 campuses',
        'Highest CTC 1 Crore reported in the placement record',
        '14,044 overall offers and 868 recruiting companies in the latest placement cycle',
        'Partnerships with 500+ foreign universities',
        '62 lakh sq. ft. built-up eco-friendly campus space',
      ],
      address: 'VIT Vellore Campus, Tiruvalam Road, Katpadi',
      city: 'Vellore',
      state: 'Tamil Nadu',
      pincode: '632014',
      country: 'India',
      phone: '044-46277555',
      email: 'ugadmission@vit.ac.in',
      admission_email: 'ugadmission@vit.ac.in',
      website: 'https://vit.ac.in',
      admissions_url: 'https://vit.ac.in/admissions/overview',
      campus_area: 'Eco-friendly campus with over 62 lakh sq. ft. built-up space',
      campus_area_acres: 250,
      total_students: 22000,
      total_faculty: 1200,
      student_faculty_ratio: '18:1',
      hostel_available: 1,
      transport_available: 1,
      logo_url: 'https://vit.ac.in/wp-content/uploads/2023/09/Layer-1-copy-2.webp',
      cover_url: 'https://vit.ac.in/wp-content/uploads/2023/07/b.tech_-1024x576.webp',
      source_url: 'https://vit.ac.in/',
    },
    departments: [
      { name: 'School of Computer Science and Engineering', code: 'SCOPE', faculty_count: 260, research_areas: 'AI & ML, Data Science, Cyber Security, Software Engineering' },
      { name: 'School of Electronics Engineering', code: 'SENSE', faculty_count: 180, research_areas: 'VLSI, Embedded Systems, Communication, Signal Processing' },
      { name: 'School of Mechanical Engineering', code: 'SMEC', faculty_count: 140, research_areas: 'Thermal, Design, Manufacturing, Automotive' },
      { name: 'School of Electrical Engineering', code: 'SELECT', faculty_count: 110, research_areas: 'Power Systems, Electric Vehicles, Control' },
      { name: 'School of Civil Engineering', code: 'SCE', faculty_count: 60, research_areas: 'Structural, Environmental, Geotechnical' },
      { name: 'School of Biotechnology & Chemical Engineering', code: 'SBST', faculty_count: 80, research_areas: 'Biomedical, Bioprocess, Chemical Engineering' },
      { name: 'School of Bio Sciences and Technology', code: 'SBST-BIO', faculty_count: 40, research_areas: 'Genomics, Microbiology, Bioinformatics' },
      { name: 'School of Information Technology & Engineering', code: 'SITE', faculty_count: 90, research_areas: 'Networks, Cloud, Software Systems' },
      { name: 'VIT Business School', code: 'VITBS', faculty_count: 60, research_areas: 'Finance, Marketing, Analytics, Operations' },
      { name: 'School of Advanced Sciences', code: 'SAS', faculty_count: 120, research_areas: 'Mathematics, Physics, Chemistry' },
      { name: 'School of Architecture', code: 'VSPARC', faculty_count: 40, research_areas: 'Architecture, Urban Design, Sustainable Building' },
      { name: 'School of Design', code: 'VITSD', faculty_count: 30, research_areas: 'Product Design, Communication Design' },
      { name: 'School of Social Sciences and Languages', code: 'SSL', faculty_count: 50, research_areas: 'English, Languages, Social Sciences' },
    ],
    courses: [
      { name: 'B.Tech. Computer Science and Engineering', code: 'BTECH-CSE', department_name: 'School of Computer Science and Engineering', level: 'UG', degree_type: 'B.Tech.', stream: 'Engineering', duration: '4 Years', intake_seats: 1200, filled_seats: 1140, eligibility: 'Pass in 10+2 with a minimum aggregate of 60% in Physics, Chemistry and Mathematics; valid VITEEE rank.', admission_criteria: 'Admission through VITEEE (VIT Engineering Entrance Examination) followed by online counselling.', entrance_exams: 'VITEEE', tuition_fee: 198000, application_fee: 1350, admission_status: 'Few Seats Left', application_deadline: '2026-10-05', specializations: 'AI & ML, Cyber Security, Data Science, IoT', syllabus_url: 'https://vit.ac.in/engineering-programmes-vellore-campus' },
      { name: 'B.Tech. Computer Science and Engineering (Specialisation in AI & ML)', code: 'BTECH-CSE-AI', department_name: 'School of Computer Science and Engineering', level: 'UG', degree_type: 'B.Tech.', stream: 'Engineering', duration: '4 Years', intake_seats: 240, filled_seats: 232, eligibility: '10+2 with 60% aggregate in PCM and a valid VITEEE rank.', admission_criteria: 'VITEEE rank and counselling', entrance_exams: 'VITEEE', tuition_fee: 228000, admission_status: 'Closing Soon', application_deadline: '2026-09-30' },
      { name: 'B.Tech. Electronics and Communication Engineering', code: 'BTECH-ECE', department_name: 'School of Electronics Engineering', level: 'UG', degree_type: 'B.Tech.', stream: 'Engineering', duration: '4 Years', intake_seats: 480, filled_seats: 430, eligibility: '10+2 with 60% aggregate in Physics, Chemistry and Mathematics; VITEEE qualified.', admission_criteria: 'VITEEE and counselling', entrance_exams: 'VITEEE', tuition_fee: 198000, admission_status: 'Open', application_deadline: '2026-10-05' },
      { name: 'B.Tech. Mechanical Engineering', code: 'BTECH-MECH', department_name: 'School of Mechanical Engineering', level: 'UG', degree_type: 'B.Tech.', stream: 'Engineering', duration: '4 Years', intake_seats: 360, filled_seats: 300, eligibility: '10+2 with 60% aggregate in PCM; VITEEE qualified.', entrance_exams: 'VITEEE', tuition_fee: 198000, admission_status: 'Open', application_deadline: '2026-10-05' },
      { name: 'B.Tech. Biotechnology', code: 'BTECH-BIO', department_name: 'School of Bio Sciences and Technology', level: 'UG', degree_type: 'B.Tech.', stream: 'Engineering', duration: '4 Years', intake_seats: 120, filled_seats: 96, eligibility: '10+2 with Biology / Mathematics along with Physics and Chemistry.', entrance_exams: 'VITEEE', tuition_fee: 198000, admission_status: 'Open' },
      { name: 'B.Sc. Computer Science / BCA', code: 'BSC-CS', department_name: 'School of Advanced Sciences', level: 'UG', degree_type: 'B.Sc. / BCA', stream: 'Science', duration: '3 Years', intake_seats: 180, filled_seats: 120, eligibility: 'Pass in 10+2 with Mathematics; direct application, no entrance examination.', admission_criteria: 'Direct admission based on Class 12 marks (no entrance exam).', tuition_fee: 125000, admission_status: 'Open', application_deadline: '2026-10-31' },
      { name: 'B.B.A.', code: 'BBA', department_name: 'VIT Business School', level: 'UG', degree_type: 'B.B.A.', stream: 'Management', duration: '3 Years', intake_seats: 120, filled_seats: 84, eligibility: 'Pass in 10+2 in any stream; direct application.', admission_criteria: 'Merit based on Class 12 marks; direct admission.', tuition_fee: 145000, admission_status: 'Open' },
      { name: 'Bachelor of Design (B.Des.)', code: 'BDES', department_name: 'School of Design', level: 'UG', degree_type: 'B.Des.', stream: 'Design', duration: '4 Years', intake_seats: 90, filled_seats: 60, eligibility: 'Pass in 10+2 in any stream; portfolio and design aptitude assessment.', admission_criteria: 'Direct application with design aptitude test and portfolio review.', tuition_fee: 210000, admission_status: 'Open' },
      { name: 'B.Arch.', code: 'BARCH', department_name: 'School of Architecture', level: 'UG', degree_type: 'B.Arch.', stream: 'Architecture', duration: '5 Years', intake_seats: 60, filled_seats: 46, eligibility: '10+2 with Mathematics and a valid NATA / JEE Paper 2 score.', entrance_exams: 'NATA, JEE Main Paper 2', tuition_fee: 240000, admission_status: 'Open' },
      { name: 'B.Sc. (Hons.) Agriculture', code: 'BSC-AGRI', department_name: 'School of Bio Sciences and Technology', level: 'UG', degree_type: 'B.Sc. (Hons.)', stream: 'Agriculture', duration: '4 Years', intake_seats: 60, filled_seats: 30, eligibility: '10+2 with Physics, Chemistry and Biology / Mathematics.', admission_criteria: 'Direct application based on Class 12 marks.', tuition_fee: 150000, admission_status: 'Open' },
      { name: 'M.Tech. (multiple specialisations)', code: 'MTECH', department_name: 'School of Computer Science and Engineering', level: 'PG', degree_type: 'M.Tech.', stream: 'Engineering', duration: '2 Years', intake_seats: 300, filled_seats: 210, eligibility: 'B.E./B.Tech. in the relevant discipline with valid VITMEE / GATE score.', entrance_exams: 'VITMEE, GATE', tuition_fee: 175000, admission_status: 'Open', application_deadline: '2026-11-10' },
      { name: 'Master of Business Administration (MBA)', code: 'MBA', department_name: 'VIT Business School', level: 'PG', degree_type: 'MBA', stream: 'Management', duration: '2 Years', intake_seats: 180, filled_seats: 140, eligibility: 'Bachelor\'s degree with minimum 60% aggregate; valid CAT / MAT / XAT / GMAT / VITBEE score.', admission_criteria: 'Entrance score followed by group discussion and personal interview.', entrance_exams: 'CAT, MAT, XAT, GMAT', tuition_fee: 320000, admission_status: 'Open' },
      { name: 'Integrated M.Tech. (5-year)', code: 'INT-MTECH', department_name: 'School of Computer Science and Engineering', level: 'Integrated', degree_type: 'Integrated M.Tech.', stream: 'Engineering', duration: '5 Years', intake_seats: 120, filled_seats: 88, eligibility: 'Pass in 10+2 with PCM; admission through VITEEE counselling.', entrance_exams: 'VITEEE', tuition_fee: 198000, admission_status: 'Open' },
    ],
    fees: [
      { course_name: 'B.Tech. Computer Science and Engineering', academic_year: '2026-27', tuition_fee: 198000, admission_fee: 12000, exam_fee: 5000, hostel_fee: 100000, other_fee: 8000, total_fee: 223000, payment_terms: 'Annual payment; semester-wise option available', scholarship_note: 'GV School Development Programme (GVSDP) merit scholarships, sports scholarships and government scholarships.' },
      { course_name: 'B.Tech. Computer Science and Engineering (Specialisation in AI & ML)', academic_year: '2026-27', tuition_fee: 228000, total_fee: 253000, hostel_fee: 100000 },
      { course_name: 'Master of Business Administration (MBA)', academic_year: '2026-27', tuition_fee: 320000, total_fee: 345000 },
    ],
    faculty: [
      { name: 'Dr. G. Viswanathan', designation: 'Founder & Chancellor', department_name: 'Administration', qualification: 'Ph.D.', is_hod: 1 },
      { name: 'Dr. Sasikumar S', designation: 'Director - UG Admissions', department_name: 'Admissions', qualification: 'Ph.D.', contact_email_note: 'ugadmission@vit.ac.in' },
    ],
    placements: [
      { academic_year: '2025-26', programme_level: 'Overall', students_graduated: 9000, students_placed: 8200, placement_percentage: 91, offers_made: 14044, companies_visited: 868, highest_package: 10000000, average_package: 950000, top_recruiter: 'TCS', notes: 'Official placement highlights: 3499 dream offers, 3003 super dream offers, 6982 regular offers, 560 marquee offers, 4051 industry internships, 14044 overall offers, 868 companies. Highest CTC 1 Crore.', source_url: 'https://vit.ac.in/cdc-highlights/' },
      { academic_year: '2024-25', programme_level: 'Overall', students_graduated: 8800, students_placed: 7900, placement_percentage: 90, offers_made: 13500, companies_visited: 830, highest_package: 8800000, average_package: 910000 },
    ],
    recruiters: [
      { name: 'TCS', sector: 'IT & Software', academic_year: '2025-26', offers_made: 4004, avg_package: 450000, is_top: 1, description: 'National record — 4004 offers.' },
      { name: 'Cognizant', sector: 'IT & Software', academic_year: '2025-26', offers_made: 1200, avg_package: 520000 },
      { name: 'Accenture', sector: 'IT & Software', academic_year: '2025-26', offers_made: 900, avg_package: 560000 },
      { name: 'Infosys', sector: 'IT & Software', academic_year: '2025-26', offers_made: 800, avg_package: 500000 },
      { name: 'Microsoft', sector: 'IT & Software', academic_year: '2025-26', offers_made: 30, avg_package: 4200000, highest_package: 10000000, is_top: 1 },
      { name: 'Amazon', sector: 'IT & Software', academic_year: '2025-26', offers_made: 120, avg_package: 3200000, is_top: 1 },
      { name: 'Qualcomm', sector: 'Core Engineering', academic_year: '2025-26', offers_made: 60, avg_package: 2400000 },
      { name: 'Deloitte', sector: 'Consulting', academic_year: '2025-26', offers_made: 220, avg_package: 850000 },
      { name: 'PayPal', sector: 'Banking & Finance', academic_year: '2025-26', offers_made: 25, avg_package: 2800000, is_top: 1 },
      { name: 'Nvidia', sector: 'IT & Software', academic_year: '2025-26', offers_made: 20, avg_package: 3000000, is_top: 1 },
    ],
    internships: [
      { company: 'VIT — industry internship programme', role: 'Industry Internship', academic_year: '2025-26', stipend: 20000, duration: '3-6 months', students_count: 4051, ppo_offers: 900, description: '4051 industry internships reported in the official placement highlights.' },
    ],
    hostels: [
      { name: 'VIT Men\'s Hostels', gender: 'Boys', capacity: 9000, room_types: 'Single, Double, Triple, Four-bedded', fees_per_year: 100000, mess_type: 'Veg & Non-Veg', amenities: 'Wi-Fi, Gym, Laundry, Medical centre, Sports facilities, Food courts', description: 'Multiple hostel blocks on campus with mess, gym and recreation facilities.' },
      { name: 'VIT Women\'s Hostels', gender: 'Girls', capacity: 7000, room_types: 'Double, Triple, Four-bedded', fees_per_year: 100000, mess_type: 'Veg & Non-Veg', amenities: 'Wi-Fi, Gym, Laundry, Medical centre, Indoor games, Security', description: 'Secure hostel blocks with warden supervision and 24x7 security.' },
    ],
    transport: [
      { route_no: 'V1', route_name: 'Vellore City – VIT Campus', stops: 'Katpadi Junction, Vellore Old Bus Stand, Chittoor Bus Stand, VIT Main Gate', fleet_count: 12, capacity: 50, daily_trips: 10, fee_per_year: 30000, gps_tracking: 1 },
      { route_no: 'V2', route_name: 'Chennai – VIT Shuttle', stops: 'Chennai, Ranipet, Walajapet, Katpadi, VIT', fleet_count: 4, daily_trips: 2, fee_per_year: 45000 },
    ],
    library: [
      { name: 'VIT Central Library (Mahatma Gandhi Central Library)', total_books: 250000, journals: 300, e_journals: 20000, e_books: 45000, digital_databases: 'IEEE, ACM, Springer, Elsevier, Scopus, Web of Science, DELNET', seating_capacity: 2000, timings: '8:00 AM – 12:00 AM (extended during examinations)', services: 'Digital library, Reference, Book bank, Reprography, Research support', description: 'Large central library with RFID automation, digital resource access and long working hours.' },
    ],
    sports: [
      { sport_name: 'Cricket', category: 'Outdoor', facilities: 'International-standard cricket ground' },
      { sport_name: 'Football', category: 'Outdoor', facilities: 'Football ground with floodlights' },
      { sport_name: 'Basketball', category: 'Outdoor', courts_count: 4 },
      { sport_name: 'Swimming', category: 'Aquatics', facilities: 'Swimming pool with coaching' },
      { sport_name: 'Gymnasium', category: 'Gymnasium', facilities: 'Modern gym with cardio and strength equipment' },
      { sport_name: 'Tennis', category: 'Outdoor', courts_count: 3 },
    ],
    infrastructure: [
      { name: 'Technology Tower', category: 'Academic Block', description: 'Multi-storey academic block housing computer science and IT schools.' },
      { name: 'VIT-TBI Technology Business Incubator', category: 'Research Centre', description: 'Incubation support for technology startups.' },
      { name: 'Centre for Innovation and Product Development', category: 'Research Centre' },
      { name: 'Anna Auditorium', category: 'Auditorium', capacity: 2000 },
      { name: 'Smart Classrooms', category: 'Digital Classroom', description: 'ICT-enabled classrooms across schools.' },
      { name: 'VIT Sports Complex', category: 'Sports Complex', description: 'Indoor and outdoor sports facilities with coaching support.' },
    ],
    facilities: [
      { name: 'Campus-wide Wi-Fi and smart classrooms', category: 'IT & Wi-Fi', available: 1 },
      { name: 'VIT Medical Centre / Hospital', category: 'Medical', available: 1, timings: '24x7 emergency support' },
      { name: 'Food courts and canteens', category: 'Canteen & Food', available: 1 },
      { name: 'Bank branches and ATMs', category: 'Bank & ATM', available: 1 },
      { name: 'Placement cell — Career Development Centre (CDC)', category: 'Placement Cell', available: 1, description: 'Training, internships and campus recruitment for all programmes.' },
      { name: 'International Relations Office', category: 'Other', available: 1, description: 'Semester abroad, joint degree and exchange programmes with 500+ partner universities.' },
      { name: 'Student counselling and wellness', category: 'Counselling', available: 1 },
      { name: 'Innovation and entrepreneurship cell', category: 'Innovation / Incubation', available: 1 },
    ],
    scholarships: [
      { name: 'GV School Development Programme (GVSDP) Merit Scholarship', provider_type: 'College', category: 'Merit', amount_type: 'Percentage of tuition fee', percent_value: 100, eligibility: 'Top rank holders in VITEEE and Class 12 board examinations; award tiers based on rank.', is_active: 1, description: 'Merit scholarships awarded to top performers, covering part or full tuition fee.' },
      { name: 'Sports Scholarship', provider_type: 'College', category: 'Sports', amount_type: 'Part fee waiver', eligibility: 'State / national level sportspersons admitted to VIT programmes.' },
      { name: 'Government scholarships (SC/ST/BC/MBC)', provider_type: 'Government', category: 'SC / ST', amount_type: 'Full tuition waiver', eligibility: 'Eligible students as per Tamil Nadu and central government scholarship schemes.' },
      { name: 'Vidya Lakshmi Education Loan support', provider_type: 'Government', category: 'Need-based', amount_type: 'Full tuition waiver', eligibility: 'Education loan assistance through the Vidya Lakshmi portal for admitted students.' },
    ],
    events: [
      { title: 'One day workshop on Structural Health Monitoring using Non-Destructive Testing (NDT) Techniques', category: 'Workshop', start_date: '2026-10-07', venue: 'VIT Vellore', status: 'Upcoming', registration_link: 'https://vit.ac.in/all-events' },
      { title: 'Two Days Executive Development Program on Next-Gen Process Engineering: AI, Waste Heat Recovery and Multi-Objective Optimization', category: 'Workshop', start_date: '2026-10-08', venue: 'VIT Vellore', status: 'Upcoming' },
      { title: 'Value Added Course on Internet of Things (VAC2355)', category: 'Workshop', start_date: '2026-08-29', venue: 'VIT Vellore', status: 'Completed' },
      { title: 'The Art of Acting (VAC-2408)', category: 'Workshop', start_date: '2026-09-17', venue: 'VIT Vellore', status: 'Upcoming' },
      { title: 'Freshers Induction Programme 2026', category: 'Orientation', start_date: '2026-07-15', venue: 'VIT Vellore', status: 'Completed', participants_count: 6000 },
    ],
    achievements: [
      { title: 'Limca Book of Records for placement records — 12th time', category: 'Placement', level: 'National', year: 2026, achieved_by: 'VIT', description: 'Recognised for unbeaten placement records.' },
      { title: '119th best institution in the world in Engineering & Technology (QS Subject Rankings)', category: 'Ranking', level: 'International', year: 2026, achieved_by: 'VIT' },
      { title: 'Top 2 in India and 501-600 globally — Shanghai ARWU 2025', category: 'Ranking', level: 'International', year: 2025, achieved_by: 'VIT', award_organisation: 'Shanghai Ranking (ARWU)' },
      { title: 'NAAC A++ accreditation', category: 'Institutional', level: 'National', year: 2021, achieved_by: 'VIT', award_organisation: 'NAAC, MHRD' },
    ],
    media: [
      { title: 'Students at the VIT Vellore campus', type: 'Image', category: 'Campus', url: 'https://vit.ac.in/wp-content/uploads/2023/07/b.tech_-1024x576.webp', is_cover: 1 },
      { title: 'Science and computer application programmes', type: 'Image', category: 'Academic', url: 'https://vit.ac.in/wp-content/uploads/2023/07/S-H-1024x576.webp' },
      { title: 'Management programmes at VIT', type: 'Image', category: 'Academic', url: 'https://vit.ac.in/wp-content/uploads/2024/05/management-1024x576.webp' },
      { title: 'BBA programme', type: 'Image', category: 'Academic', url: 'https://vit.ac.in/wp-content/uploads/2024/05/bba-1024x576.webp' },
      { title: 'VIT admissions counselling', type: 'Image', category: 'Gallery', url: 'https://vit.ac.in/wp-content/uploads/2024/01/home-page-admission-1024x823.webp' },
      { title: 'Events at VIT Vellore', type: 'Image', category: 'Event', url: 'https://vit.ac.in/wp-content/uploads/2023/11/event-image-home-1024x960.webp' },
      { title: 'VIT campus and rankings', type: 'Image', category: 'Campus', url: 'https://vit.ac.in/wp-content/uploads/2025/09/nirf-rank-2025-web-thum.webp' },
    ],
    documents: [
      { title: 'UG admissions overview', category: 'Brochure', year: '2026', file_url: 'https://vit.ac.in/admissions/overview' },
      { title: 'UG programmes and fee structure', category: 'Fee Structure', year: '2026', file_url: 'https://vit.ac.in/admission/ug/fee-structure' },
      { title: 'Placement highlights (Career Development Centre)', category: 'Placement Report', year: '2026', file_url: 'https://vit.ac.in/cdc-highlights/' },
      { title: 'UG courses downloads', category: 'Prospectus', year: '2026', file_url: 'https://vit.ac.in/ug-downloads' },
    ],
  },

  /* ------------------------------------------------------------------ */
  {
    account: { username: 'loyola', email: 'helpdesk@loyolacollege.edu', password: 'Loyola@Login2026', full_name: 'Admissions Helpdesk', designation: 'Admission Officer' },
    college: {
      name: 'Loyola College',
      short_name: 'Loyola Chennai',
      type: 'Private Aided',
      ownership: 'Society of Jesus (Jesuits), Chennai Province',
      established_year: 1925,
      affiliation: 'University of Madras',
      accreditation: 'NAAC accredited; College with Potential for Excellence',
      approval_body: 'UGC, AICTE (for select programmes)',
      nirf_rank: 'Consistently ranked among the top arts & science colleges in India (NIRF)',
      motto: 'Let Your Light Shine',
      about:
        'Loyola College, Chennai was established in 1925 by the Society of Jesus and is affiliated to the University of Madras. The college is a premier institution for arts, science and commerce education with UG, PG and research programmes, offering more than 30 departments, vocational education through LIVE (Loyola Institute of Vocational Education) and a strong record in research, extension and placement.',
      vision: 'To form intellectually competent, morally upright, socially committed, spiritually inspired men and women who will build a just and humane society.',
      mission:
        'To provide holistic education that integrates academic excellence with ethical values and social responsibility, especially for the marginalised; to promote research and innovation; and to serve the neighbourhood and society through extension activities.',
      highlights: [
        'Established 1925, affiliated to the University of Madras',
        'Motto: "Let Your Light Shine"',
        'UG, PG, M.Phil., Ph.D. and vocational programmes (LIVE)',
        'On-campus men\'s and women\'s hostels with dedicated admission portals',
        'Active research, extension, sports and cultural programmes',
      ],
      address: 'Sterling Road, Nungambakkam',
      city: 'Chennai',
      state: 'Tamil Nadu',
      pincode: '600034',
      country: 'India',
      phone: '044-28178200',
      email: 'helpdesk@loyolacollege.edu',
      admission_email: 'helpdesk@loyolacollege.edu',
      website: 'https://www.loyolacollege.edu',
      admissions_url: 'https://admission.loyolacollege.edu/lccadmission/',
      total_students: 12000,
      campus_area: 'Urban campus in the heart of Chennai',
      hostel_available: 1,
      transport_available: 1,
      logo_url: 'https://www.loyolacollege.edu/images/logo.png',
      cover_url: 'https://www.loyolacollege.edu/events/AY25-26/LIVE/thumbnail/6aab6d807653f_013f1a9835b6b1fe.jpeg',
      source_url: 'https://www.loyolacollege.edu/',
    },
    departments: [
      { name: 'PG and Research Department of Commerce', code: 'COM', faculty_count: 40, research_areas: 'Accounting, Finance, Taxation, Business Analytics' },
      { name: 'PG and Research Department of English', code: 'ENG', faculty_count: 35, research_areas: 'Literature, Linguistics, Communication' },
      { name: 'PG and Research Department of Economics', code: 'ECO', faculty_count: 25, research_areas: 'Development Economics, Econometrics, Public Policy' },
      { name: 'Department of Computer Science', code: 'CSC', faculty_count: 30, research_areas: 'Data Science, AI, Software Engineering' },
      { name: 'Department of Physics', code: 'PHY', faculty_count: 22, research_areas: 'Materials, Spectroscopy, Electronics' },
      { name: 'Department of Chemistry', code: 'CHE', faculty_count: 24, research_areas: 'Organic, Inorganic, Physical Chemistry' },
      { name: 'Department of Mathematics', code: 'MAT', faculty_count: 26, research_areas: 'Algebra, Analysis, Statistics' },
      { name: 'Department of Advanced Zoology and Biotechnology', code: 'ADVZOO', faculty_count: 20, research_areas: 'Vector biology, Biotechnology, Ecology' },
      { name: 'Department of Plant Biology and Biotechnology', code: 'PBB', faculty_count: 18, research_areas: 'Plant taxonomy, Plant tissue culture' },
      { name: 'Department of Statistics', code: 'STA', faculty_count: 14, research_areas: 'Applied Statistics, Data Analytics' },
      { name: 'Department of Visual Communication', code: 'VISCOM', faculty_count: 16, research_areas: 'Film, Animation, Media Studies' },
      { name: 'Department of Social Work', code: 'SW', faculty_count: 18, research_areas: 'Community development, Medical and psychiatric social work' },
      { name: 'Department of Hindi', code: 'HIN', faculty_count: 8, research_areas: 'Hindi literature, Language teaching' },
      { name: 'Department of Tamil', code: 'TAM', faculty_count: 14, research_areas: 'Tamil literature, Comparative studies' },
      { name: 'Loyola Institute of Business Administration (LIBA)', code: 'LIBA', faculty_count: 26, research_areas: 'Business management, Analytics' },
      { name: 'Loyola Institute of Vocational Education (LIVE)', code: 'LIVE', faculty_count: 20, research_areas: 'Vocational and skill education' },
      { name: 'Loyola Institute of Social Science Training and Research (LISSTAR)', code: 'LISSTAR', faculty_count: 12, research_areas: 'Social science research and training' },
    ],
    courses: [
      { name: 'B.Com. (General)', code: 'BCOM', department_name: 'PG and Research Department of Commerce', level: 'UG', degree_type: 'B.Com.', stream: 'Commerce', duration: '3 Years', intake_seats: 240, filled_seats: 232, eligibility: 'Pass in 10+2 (Commerce / Accountancy preferred) with the prescribed minimum marks; admission through the college\'s online application and merit list.', admission_criteria: 'Merit based on Class 12 marks through the online admission portal.', tuition_fee: 42000, admission_status: 'Closing Soon', application_deadline: '2026-09-28' },
      { name: 'B.Com. (Honours / Accounting & Finance)', code: 'BCOM-AF', department_name: 'PG and Research Department of Commerce', level: 'UG', degree_type: 'B.Com.', stream: 'Commerce', duration: '3 Years', intake_seats: 120, filled_seats: 116, eligibility: '10+2 Commerce with high marks in Accountancy and Business Mathematics.', admission_criteria: 'Merit based admission on Class 12 marks.', tuition_fee: 48000, admission_status: 'Few Seats Left', application_deadline: '2026-09-28' },
      { name: 'B.A. English Literature', code: 'BA-ENG', department_name: 'PG and Research Department of English', level: 'UG', degree_type: 'B.A.', stream: 'Arts', duration: '3 Years', intake_seats: 120, filled_seats: 98, eligibility: 'Pass in 10+2 in any stream with proficiency in English.', admission_criteria: 'Merit based admission through the online portal.', tuition_fee: 36000, admission_status: 'Open', application_deadline: '2026-10-05' },
      { name: 'B.A. Economics', code: 'BA-ECO', department_name: 'PG and Research Department of Economics', level: 'UG', degree_type: 'B.A.', stream: 'Arts', duration: '3 Years', intake_seats: 90, filled_seats: 70, eligibility: '10+2 with Mathematics / Economics preferred.', tuition_fee: 36000, admission_status: 'Open' },
      { name: 'B.Sc. Computer Science', code: 'BSC-CS', department_name: 'Department of Computer Science', level: 'UG', degree_type: 'B.Sc.', stream: 'Science', duration: '3 Years', intake_seats: 120, filled_seats: 112, eligibility: '10+2 with Mathematics and Computer Science / Maths with Physics.', admission_criteria: 'Merit based on Class 12 marks.', tuition_fee: 45000, admission_status: 'Few Seats Left', application_deadline: '2026-09-30' },
      { name: 'B.Sc. Visual Communication', code: 'BSC-VISCOM', department_name: 'Department of Visual Communication', level: 'UG', degree_type: 'B.Sc.', stream: 'Media', duration: '3 Years', intake_seats: 60, filled_seats: 42, eligibility: 'Pass in 10+2; aptitude for media and communication.', tuition_fee: 52000, admission_status: 'Open' },
      { name: 'B.Sc. Biotechnology', code: 'BSC-BIO', department_name: 'Department of Advanced Zoology and Biotechnology', level: 'UG', degree_type: 'B.Sc.', stream: 'Science', duration: '3 Years', intake_seats: 60, filled_seats: 44, eligibility: '10+2 with Biology / Botany & Zoology and Chemistry.', tuition_fee: 46000, admission_status: 'Open' },
      { name: 'B.B.A.', code: 'BBA', department_name: 'PG and Research Department of Commerce', level: 'UG', degree_type: 'B.B.A.', stream: 'Management', duration: '3 Years', intake_seats: 90, filled_seats: 66, eligibility: 'Pass in 10+2 in any stream.', tuition_fee: 50000, admission_status: 'Open' },
      { name: 'M.Com.', code: 'MCOM', department_name: 'PG and Research Department of Commerce', level: 'PG', degree_type: 'M.Com.', stream: 'Commerce', duration: '2 Years', intake_seats: 60, filled_seats: 48, eligibility: 'B.Com. / B.B.A. / B.Com.(AF) with the prescribed minimum marks.', admission_criteria: 'Merit based on degree marks; entrance / interview if required.', tuition_fee: 38000, admission_status: 'Open', application_deadline: '2026-10-15' },
      { name: 'M.A. English', code: 'MA-ENG', department_name: 'PG and Research Department of English', level: 'PG', degree_type: 'M.A.', stream: 'Arts', duration: '2 Years', intake_seats: 40, filled_seats: 34, eligibility: 'B.A. English or equivalent with minimum 50% marks.', admission_criteria: 'Merit based, with an entrance test and interview.', tuition_fee: 36000, admission_status: 'Open' },
      { name: 'M.Sc. Computer Science / Data Science', code: 'MSC-CS', department_name: 'Department of Computer Science', level: 'PG', degree_type: 'M.Sc.', stream: 'Science', duration: '2 Years', intake_seats: 40, filled_seats: 30, eligibility: 'B.Sc. Computer Science / Mathematics / related degree.', tuition_fee: 48000, admission_status: 'Open' },
      { name: 'Master of Social Work (MSW)', code: 'MSW', department_name: 'Department of Social Work', level: 'PG', degree_type: 'MSW', stream: 'Social Work', duration: '2 Years', intake_seats: 60, filled_seats: 40, eligibility: 'Bachelor\'s degree in any discipline; aptitude for social work.', tuition_fee: 40000, admission_status: 'Open' },
      { name: 'Ph.D. / M.Phil. Research Programmes', code: 'PHD', department_name: 'Research', level: 'Doctorate', degree_type: 'Ph.D. / M.Phil.', stream: 'Research', duration: '2-5 Years', intake_seats: 60, filled_seats: 22, eligibility: 'Master\'s degree with minimum 55% marks; entrance test and interview as per University of Madras norms.', admission_criteria: 'Research entrance test conducted by the college / university followed by interview.', admission_status: 'Open' },
      { name: 'Diploma & Vocational Programmes (LIVE)', code: 'LIVE-DIP', department_name: 'Loyola Institute of Vocational Education (LIVE)', level: 'Diploma', degree_type: 'Diploma', stream: 'Vocational', duration: '1 Year', intake_seats: 200, filled_seats: 120, eligibility: 'Pass in 10+2; programme-specific requirements.', admission_criteria: 'Direct admission through the LIVE online application portal.', tuition_fee: 30000, admission_status: 'Open', application_deadline: '2026-10-31' },
    ],
    fees: [
      { course_name: 'B.Com. (General)', academic_year: '2026-27', tuition_fee: 42000, admission_fee: 3000, exam_fee: 2000, library_fee: 1000, hostel_fee: 60000, total_fee: 48000, payment_terms: 'Annual payment at admission; second instalment in January where applicable.', scholarship_note: 'Government SC/ST/BC-ADX scholarships (LSSS office), minority and management scholarships available.' },
      { course_name: 'B.Sc. Computer Science', academic_year: '2026-27', tuition_fee: 45000, total_fee: 51000, hostel_fee: 60000 },
      { course_name: 'M.Com.', academic_year: '2026-27', tuition_fee: 38000, total_fee: 44000 },
    ],
    faculty: [],
    placements: [
      { academic_year: '2025-26', programme_level: 'Overall', students_graduated: 3200, students_placed: 2100, placement_percentage: 66, offers_made: 2600, companies_visited: 260, highest_package: 1200000, average_package: 420000, top_recruiter: 'Deloitte', notes: 'Indicative figures for the placement cell; confirm the official placement report before publishing.', source_url: 'https://www.loyolacollege.edu/' },
    ],
    recruiters: [
      { name: 'Deloitte', sector: 'Consulting', academic_year: '2025-26', offers_made: 60, avg_package: 600000 },
      { name: 'TCS', sector: 'IT & Software', academic_year: '2025-26', offers_made: 320, avg_package: 420000 },
      { name: 'Cognizant', sector: 'IT & Software', academic_year: '2025-26', offers_made: 180, avg_package: 450000 },
      { name: 'Zoho', sector: 'IT & Software', academic_year: '2025-26', offers_made: 90, avg_package: 650000 },
      { name: 'Wipro', sector: 'IT & Software', academic_year: '2025-26', offers_made: 140, avg_package: 400000 },
      { name: 'EY', sector: 'Banking & Finance', academic_year: '2025-26', offers_made: 40, avg_package: 700000 },
    ],
    internships: [
      { company: 'Loyola Institute of Vocational Education (LIVE) — Agentic AI Internship Program', role: 'AI Internship', academic_year: '2025-26', stipend: 15000, duration: '3 months', students_count: 40, mode: 'Hybrid', description: 'Internship programme announced by LIVE for students interested in agentic AI.', application_link: 'https://live.loyolacollege.edu/' },
    ],
    hostels: [
      { name: "Loyola College Men's Hostel", gender: 'Boys', capacity: 500, room_types: 'Single, Double, Triple', fees_per_year: 60000, mess_type: 'Veg & Non-Veg', amenities: 'Study halls, Wi-Fi, Chapel, Sports, Laundry', description: 'Hostel managed by the college with a dedicated online admission portal.' },
      { name: "Loyola College Women's Hostel", gender: 'Girls', capacity: 400, room_types: 'Double, Triple', fees_per_year: 60000, mess_type: 'Veg & Non-Veg', amenities: 'Study halls, Wi-Fi, Chapel, Indoor games, 24x7 security', description: 'On-campus women\'s hostel with separate online application portal.' },
    ],
    transport: [
      { route_no: 'L1', route_name: 'Tambaram – Nungambakkam (College)', stops: 'Tambaram, Chromepet, Guindy, Saidapet, Nungambakkam', fleet_count: 3, daily_trips: 2, fee_per_year: 26000 },
      { route_no: 'L2', route_name: 'Anna Nagar – Nungambakkam (College)', stops: 'Anna Nagar, Aminjikarai, Kilpauk, Egmore, Nungambakkam', fleet_count: 3, daily_trips: 2, fee_per_year: 24000 },
    ],
    library: [
      { name: 'Loyola College Central Library (Bertram Hall)', total_books: 180000, journals: 200, e_journals: 6000, e_books: 12000, digital_databases: 'N-LIST, DELNET, JSTOR, Springer, Scopus', seating_capacity: 700, timings: '8:30 AM – 7:00 PM', services: 'Reference, Book bank, Reprography, Digital resources, Reading halls', description: 'The central library is housed in the heritage Library Building and supports all departments with print and digital collections.' },
    ],
    sports: [
      { sport_name: 'Cricket', category: 'Outdoor', facilities: 'Cricket ground with practice nets' },
      { sport_name: 'Basketball', category: 'Outdoor', courts_count: 2 },
      { sport_name: 'Football', category: 'Outdoor', facilities: 'Football field' },
      { sport_name: 'Volleyball', category: 'Outdoor', courts_count: 2 },
      { sport_name: 'Table Tennis', category: 'Indoor', courts_count: 4 },
      { sport_name: 'Gymnasium', category: 'Gymnasium', facilities: 'Gym with weight-training and cardio equipment' },
    ],
    infrastructure: [
      { name: 'Bertram Hall (Central Library Building)', category: 'Academic Block', description: 'Heritage building housing the central library and conference halls.' },
      { name: 'Lawrence Sundaram Hall', category: 'Seminar Hall', capacity: 500, description: 'Jubilee Building hall used for conferences and seminars.' },
      { name: 'Y D Hall (Chemistry Block)', category: 'Seminar Hall', capacity: 200 },
      { name: 'LIAC Conference Hall', category: 'Seminar Hall', capacity: 150, description: 'Commerce and Economics Building conference hall.' },
      { name: 'Beschi Hall', category: 'Seminar Hall', capacity: 200 },
      { name: 'Science laboratories and research centres', category: 'Laboratory', description: 'Departmental laboratories for physical, life and chemical sciences.' },
    ],
    facilities: [
      { name: 'Central Library and digital resources', category: 'IT & Wi-Fi', available: 1 },
      { name: 'Campus Wi-Fi and computer labs', category: 'IT & Wi-Fi', available: 1 },
      { name: 'Loyola College Health Centre', category: 'Medical', available: 1 },
      { name: 'Canteen and food courts', category: 'Canteen & Food', available: 1 },
      { name: 'Bank branch and ATM on campus', category: 'Bank & ATM', available: 1 },
      { name: 'Placement and career guidance cell', category: 'Placement Cell', available: 1 },
      { name: 'Campus map and security services', category: 'Security', available: 1, description: 'Campus map, visitor management and 24x7 security.' },
      { name: 'Loyola Institute of Vocational Education (LIVE)', category: 'Other', available: 1, description: 'Vocational and skill-based diploma programmes for students and the community.' },
    ],
    scholarships: [
      { name: 'Government of Tamil Nadu SC/ST/(BC-ADX) Scholarship', provider_type: 'Government', category: 'SC / ST', amount_type: 'Full tuition waiver', eligibility: 'Eligible students as per government norms; applications processed through the LSSS office of the college.', description: 'Advertised by the college for the academic year 2026-27.' },
      { name: 'Minority Scholarship', provider_type: 'Government', category: 'Minority', amount_type: 'Part fee waiver', eligibility: 'Students from minority communities as per central government scholarship schemes.' },
      { name: 'Loyola Endowment and Management Scholarships', provider_type: 'Trust', category: 'Need-based', amount_type: 'Fixed amount', eligibility: 'Economically disadvantaged students with good academic records; selection by the scholarship committee.' },
    ],
    events: [
      { title: 'AGENTIC AI — Internship Program', category: 'Workshop', start_date: '2026-09-25', venue: 'Loyola Institute of Vocational Education (LIVE)', status: 'Upcoming', registration_link: 'https://live.loyolacollege.edu/' },
      { title: 'Hindi Day Celebration — Hindi and Employment Opportunities in the Global Scenario', category: 'Seminar', start_date: '2026-09-25', venue: 'Beschi Hall, Commerce and Economics Building', status: 'Upcoming' },
      { title: 'Ph.D. Public Viva Voce Examination — Ms. S. Cyrene Thanga Blessy', category: 'Seminar', start_date: '2026-09-28', venue: 'Lawrence Sundaram Hall, Jubilee Building', status: 'Upcoming' },
      { title: 'Two-Day National Conference — Digital Agenda and Artificial Intelligence (AI) to Redesign Tourism', category: 'Conference', start_date: '2026-09-30', end_date: '2026-10-01', venue: 'Lawrence Sundaram Hall, Jubilee Building', status: 'Upcoming', chief_guest: 'Organised by LISSTAR' },
      { title: 'TRAVELTECH 2026 | Student Innovation', category: 'Technical', start_date: '2026-09-30', end_date: '2026-11-01', venue: 'Loyola College', status: 'Upcoming', chief_guest: 'LISSTAR' },
      { title: 'International Conference on Life Sciences and Vector Risk Management for a Sustainable Healthy Environment', category: 'Conference', start_date: '2026-11-26', end_date: '2026-11-28', venue: 'Bertram Hall, Library Building', status: 'Upcoming', chief_guest: 'Department of Advanced Zoology and Biotechnology' },
      { title: 'International Conference on Business Transformation for a Sustainable and Intelligent Future', category: 'Conference', start_date: '2026-11-26', end_date: '2026-11-27', venue: 'Lawrence Sundaram Hall, Jubilee Building', status: 'Upcoming', chief_guest: 'PG and Research Department of Commerce' },
      { title: "OVATIONS '26 — Cultural Fest", category: 'Cultural', start_date: '2026-10-20', venue: 'Loyola College Campus', status: 'Upcoming', registration_link: 'https://ovations-lumiera.vercel.app/' },
    ],
    achievements: [
      { title: 'College with Potential for Excellence', category: 'Institutional', level: 'National', achieved_by: 'Loyola College', award_organisation: 'UGC' },
      { title: 'Consistently ranked among India\'s top arts and science colleges (NIRF)', category: 'Ranking', level: 'National', year: 2025, achieved_by: 'Loyola College' },
    ],
    media: [
      { title: 'Agentic AI Internship Program announcement', type: 'Image', category: 'Event', url: 'https://www.loyolacollege.edu/events/AY25-26/LIVE/thumbnail/6aab6d807653f_013f1a9835b6b1fe.jpeg', is_cover: 1 },
      { title: 'International Conference on Life Sciences and Vector Risk Management', type: 'Image', category: 'Event', url: 'https://www.loyolacollege.edu/events/AY25-26/ADVZOO/thumbnail/6a83eb5bb4959_94f6183ec456a749.jpg' },
      { title: 'Business Transformation conference', type: 'Image', category: 'Event', url: 'https://www.loyolacollege.edu/events/AY25-26/COM1/thumbnail/6a9682969a07c_77a0484c2a544039.jpg' },
      { title: 'Ph.D. Public Viva Voce — Department of English', type: 'Image', category: 'Academic', url: 'https://www.loyolacollege.edu/events/AY25-26/ENG1/thumbnail/6ab0c43729a90_26be46da024bbd49.jpg' },
      { title: 'TRAVELTECH 2026 Student Innovation', type: 'Image', category: 'Event', url: 'https://www.loyolacollege.edu/events/AY25-26/LISSTAR/thumbnail/6aabd92948550_54630a689166b596.jpg' },
      { title: 'Hindi Day Celebration', type: 'Image', category: 'Event', url: 'https://www.loyolacollege.edu/events/AY25-26/HINDI1/thumbnail/6ab1411a9d3aa_f3bb0867b282a01e.jpeg' },
    ],
    documents: [
      { title: 'UG and PG admissions portal', category: 'Admission Form', year: '2026', file_url: 'https://admission.loyolacollege.edu/lccadmission/' },
      { title: 'Academic calendar', category: 'Academic Calendar', year: '2026', file_url: 'https://www.loyolacollege.edu/acnew' },
      { title: 'Central library profile', category: 'Other', year: '2026', file_url: 'https://www.loyolacollege.edu/library/profile' },
      { title: 'Campus map', category: 'Other', year: '2026', file_url: 'https://www.loyolacollege.edu/campusmap' },
    ],
  },

  /* ------------------------------------------------------------------ */
  {
    account: { username: 'iitm', email: 'academics@iitm.ac.in', password: 'IITM@Login2026', full_name: 'Academic Office', designation: 'Academic Programme Officer' },
    college: {
      name: 'Indian Institute of Technology Madras',
      short_name: 'IIT Madras',
      type: 'Government',
      ownership: 'Government of India (Institute of Eminence)',
      established_year: 1959,
      affiliation: 'Institute of National Importance',
      accreditation: 'Institution of Eminence; NAAC accredited',
      approval_body: 'Ministry of Education, Government of India; Institute of Eminence',
      nirf_rank: 'Ranked No. 1 in India (NIRF) for nine consecutive years',
      motto: 'Siddhirbhavati Karmaja',
      about:
        'Indian Institute of Technology Madras (IIT Madras) was established in 1959 as an institute of national importance. IIT Madras offers B.Tech., dual degree, interdisciplinary masters, MS, MBA, Ph.D. and online programmes across engineering, sciences, humanities and management, and is consistently ranked first among Indian institutions in the NIRF rankings. The institute is known for research parks, incubation, the online BSc degree programme and international campuses.',
      vision: 'To be a globally recognised institute that advances knowledge through research and education, and contributes to the technological and socio-economic development of the nation.',
      mission:
        'Deliver quality education in engineering, science and management; pursue research and innovation of international standards; foster entrepreneurship and industry collaboration; and serve society through technology incubation and outreach.',
      highlights: [
        'Ranked No. 1 in India (NIRF Engineering) for nine consecutive years',
        'Institute of Eminence, established 1959',
        'Research Park and incubation ecosystem',
        'Pioneer of the online B.Sc. Degree Programme (BS Data Science and Applications)',
        'International campus at Zanzibar and global academic partnerships',
      ],
      address: 'IIT P.O., Adyar',
      city: 'Chennai',
      state: 'Tamil Nadu',
      pincode: '600036',
      country: 'India',
      phone: '+91 44 2257 8000',
      email: 'academics@iitm.ac.in',
      admission_email: 'academics@iitm.ac.in',
      website: 'https://www.iitm.ac.in',
      admissions_url: 'https://www.iitm.ac.in/academics/admissions',
      campus_area: '617 acres',
      campus_area_acres: 617,
      hostel_available: 1,
      transport_available: 1,
      logo_url: 'https://www.iitm.ac.in/sites/default/files/logo_0.png',
      cover_url: 'https://www.iitm.ac.in/sites/default/files/styles/img_s5/public/happenings/press_release/pressrelease21_09_2026_12_12.jpg?itok=3rYMLOE5',
      source_url: 'https://www.iitm.ac.in/',
    },
    departments: [
      { name: 'Department of Computer Science and Engineering', code: 'CSE', research_areas: 'AI, Machine Learning, Systems, Theory' },
      { name: 'Department of Electrical Engineering', code: 'EE', research_areas: 'Power systems, Communications, Photonics' },
      { name: 'Department of Mechanical Engineering', code: 'ME', research_areas: 'Thermal, Design, Manufacturing, Robotics' },
      { name: 'Department of Civil Engineering', code: 'CE', research_areas: 'Structures, Geotechnical, Environmental, Transportation' },
      { name: 'Department of Aerospace Engineering', code: 'AE', research_areas: 'Aerodynamics, Propulsion, Structures' },
      { name: 'Department of Chemical Engineering', code: 'CHE', research_areas: 'Process systems, Reaction engineering' },
      { name: 'Department of Metallurgical and Materials Engineering', code: 'MME', research_areas: 'Materials, Metallurgy, Corrosion' },
      { name: 'Department of Ocean Engineering', code: 'OE', research_areas: 'Autonomous ships, Offshore structures, Naval architecture' },
      { name: 'Department of Biotechnology', code: 'BT', research_areas: 'Biomedical, Bioprocess, Computational biology' },
      { name: 'Department of Physics', code: 'PHY', research_areas: 'Condensed matter, Quantum computing' },
      { name: 'Department of Mathematics', code: 'MAT', research_areas: 'Applied mathematics, Data science foundations' },
      { name: 'Department of Management Studies', code: 'DOMS', research_areas: 'Business analytics, Strategy, Operations' },
      { name: 'Centre for Cybersecurity and Digital Forensics', code: 'CCSF', research_areas: 'Cybersecurity, Digital forensics' },
    ],
    courses: [
      { name: 'B.Tech. Computer Science and Engineering', code: 'BTECH-CSE', department_name: 'Department of Computer Science and Engineering', level: 'UG', degree_type: 'B.Tech.', stream: 'Engineering', duration: '4 Years', intake_seats: 120, filled_seats: 120, eligibility: 'Pass in 10+2 with Physics, Chemistry and Mathematics; admission through JEE (Advanced) as per JoSAA counselling.', admission_criteria: 'JEE Advanced rank through JoSAA / institute counselling.', entrance_exams: 'JEE Advanced', tuition_fee: 220000, application_fee: 2000, admission_status: 'Closed', application_deadline: '2026-06-30', syllabus_url: 'https://www.iitm.ac.in/academics' },
      { name: 'B.Tech. Electrical Engineering', code: 'BTECH-EE', department_name: 'Department of Electrical Engineering', level: 'UG', degree_type: 'B.Tech.', stream: 'Engineering', duration: '4 Years', intake_seats: 80, filled_seats: 80, eligibility: '10+2 with PCM and a valid JEE (Advanced) rank.', entrance_exams: 'JEE Advanced', tuition_fee: 220000, admission_status: 'Closed' },
      { name: 'B.Tech. Mechanical Engineering', code: 'BTECH-ME', department_name: 'Department of Mechanical Engineering', level: 'UG', degree_type: 'B.Tech.', stream: 'Engineering', duration: '4 Years', intake_seats: 90, filled_seats: 90, eligibility: '10+2 with PCM and a valid JEE (Advanced) rank.', entrance_exams: 'JEE Advanced', tuition_fee: 220000, admission_status: 'Closed' },
      { name: 'B.Tech. Aerospace Engineering', code: 'BTECH-AE', department_name: 'Department of Aerospace Engineering', level: 'UG', degree_type: 'B.Tech.', stream: 'Engineering', duration: '4 Years', intake_seats: 50, filled_seats: 48, eligibility: '10+2 with PCM and a valid JEE (Advanced) rank.', entrance_exams: 'JEE Advanced', tuition_fee: 220000, admission_status: 'Closed' },
      { name: 'Bachelor of Cybersecurity (BS)', code: 'BS-CYBER', department_name: 'Centre for Cybersecurity and Digital Forensics', level: 'UG', degree_type: 'BS', stream: 'Engineering', duration: '4 Years', intake_seats: 60, filled_seats: 32, eligibility: 'As notified by the institute for the Bachelor of Cybersecurity programme; entrance test / qualifying examination as announced.', admission_criteria: 'Institute admissions process for the Bachelor of Cybersecurity programme.', admission_status: 'Open', application_deadline: '2026-11-15' },
      { name: 'BS in Medical Sciences and Engineering', code: 'BS-MSE', department_name: 'Department of Biotechnology', level: 'UG', degree_type: 'BS', stream: 'Medical Sciences & Engineering', duration: '4 Years', intake_seats: 40, filled_seats: 24, eligibility: '10+2 with Biology / Mathematics along with Physics and Chemistry; admission as per the MST programme notification.', admission_status: 'Open', application_deadline: '2026-11-30' },
      { name: 'Online B.Sc. in Data Science and Applications', code: 'BSC-ONLINE', department_name: 'Department of Mathematics', level: 'UG', degree_type: 'B.Sc. (Online)', stream: 'Science', duration: '3 Years', intake_seats: 1000, filled_seats: 640, eligibility: 'Pass in Class 12 (any stream) with Mathematics / Statistics in Class 10 or 12; no entrance examination, qualification-based entry.', admission_criteria: 'Qualifier process — 4 weeks of coursework followed by qualifier exams.', tuition_fee: 250000, admission_status: 'Open', application_deadline: '2026-12-15', mode: 'Online' },
      { name: 'M.Tech. (multiple departments)', code: 'MTECH', department_name: 'Department of Computer Science and Engineering', level: 'PG', degree_type: 'M.Tech.', stream: 'Engineering', duration: '2 Years', intake_seats: 400, filled_seats: 320, eligibility: 'B.E./B.Tech. with a valid GATE score in the relevant discipline.', admission_criteria: 'GATE score based admission, with written test / interview where applicable.', entrance_exams: 'GATE', tuition_fee: 60000, admission_status: 'Open', application_deadline: '2026-11-20' },
      { name: 'Interdisciplinary Masters Programme (I2MP)', code: 'I2MP', department_name: 'Department of Mechanical Engineering', level: 'PG', degree_type: 'M.Tech. (Interdisciplinary)', stream: 'Interdisciplinary', duration: '2 Years', intake_seats: 60, filled_seats: 30, eligibility: 'Bachelor\'s degree in engineering or science as specified for each stream; open to international applicants.', admission_status: 'Open' },
      { name: 'Master of Business Administration (MBA)', code: 'MBA', department_name: 'Department of Management Studies', level: 'PG', degree_type: 'MBA', stream: 'Management', duration: '2 Years', intake_seats: 80, filled_seats: 60, eligibility: 'Bachelor\'s degree with a valid CAT score (and institute interview process).', entrance_exams: 'CAT', tuition_fee: 400000, admission_status: 'Open', application_deadline: '2026-12-10' },
      { name: 'Ph.D. / MS Research Programmes', code: 'PHD', department_name: 'Research', level: 'Doctorate', degree_type: 'Ph.D. / M.S.', stream: 'Research', duration: '3-5 Years', intake_seats: 500, filled_seats: 240, eligibility: 'Bachelor\'s or Master\'s degree in the relevant discipline with valid GATE / CSIR / UGC / institute test scores as applicable.', admission_criteria: 'Research admissions twice a year with written test and interview by the department.', admission_status: 'Open', application_deadline: '2026-11-25' },
    ],
    fees: [
      { course_name: 'B.Tech. Computer Science and Engineering', academic_year: '2026-27', tuition_fee: 220000, admission_fee: 5000, exam_fee: 2000, hostel_fee: 60000, total_fee: 227000, payment_terms: 'Semester-wise payment', scholarship_note: 'Merit-cum-means scholarships, institute free studentships and government scholarships; full fee waiver for eligible family income criteria.' },
      { course_name: 'Online B.Sc. in Data Science and Applications', academic_year: '2026-27', tuition_fee: 250000, total_fee: 250000, payment_terms: 'Programme fee payable in parts as per notification' },
    ],
    faculty: [
      { name: 'Prof. V. Kamakoti', designation: 'Director', department_name: 'Administration', qualification: 'Ph.D.', is_hod: 1 },
    ],
    placements: [
      { academic_year: '2025-26', programme_level: 'Overall', students_graduated: 2500, students_placed: 2200, placement_percentage: 88, offers_made: 2700, companies_visited: 400, highest_package: 6000000, average_package: 1800000, top_recruiter: 'Microsoft', notes: 'Indicative figures from the institute placement cell; confirm the official placement report before publishing.', source_url: 'https://www.iitm.ac.in/' },
    ],
    recruiters: [
      { name: 'Microsoft', sector: 'IT & Software', academic_year: '2025-26', offers_made: 25, avg_package: 4000000, is_top: 1 },
      { name: 'Google', sector: 'IT & Software', academic_year: '2025-26', offers_made: 15, avg_package: 4500000, is_top: 1 },
      { name: 'Qualcomm', sector: 'Core Engineering', academic_year: '2025-26', offers_made: 40, avg_package: 2800000 },
      { name: 'Texas Instruments', sector: 'Core Engineering', academic_year: '2025-26', offers_made: 30, avg_package: 2600000 },
      { name: 'Goldman Sachs', sector: 'Banking & Finance', academic_year: '2025-26', offers_made: 20, avg_package: 3500000, is_top: 1 },
      { name: 'Bain & Company', sector: 'Consulting', academic_year: '2025-26', offers_made: 12, avg_package: 3200000 },
      { name: 'TCS Research', sector: 'IT & Software', academic_year: '2025-26', offers_made: 60, avg_package: 1200000 },
    ],
    internships: [
      { company: 'Summer Fellowship Programme', role: 'Research Intern', academic_year: '2025-26', stipend: 15000, duration: '8 weeks', students_count: 150, eligibility: 'Students from IITs and other institutions based on academic performance', description: 'Summer research fellowship across departments and centres.' },
    ],
    hostels: [
      { name: 'IIT Madras Hostels of Residence', gender: 'Co-ed', capacity: 9000, room_types: 'Single, Double, Triple', fees_per_year: 60000, mess_type: 'Veg & Non-Veg', amenities: 'Wi-Fi, Mess, Gym, Reading rooms, Sports, Medical centre, Laundry', description: 'Hostels of Residence with separate blocks for men and women, mess facilities and wardens.' },
    ],
    transport: [
      { route_no: 'I1', route_name: 'Campus – Adyar / Guindy shuttle', stops: 'Adyar, Madhya Kailash, Guindy, IIT Main Gate', daily_trips: 20, fee_per_year: 12000, gps_tracking: 1 },
    ],
    library: [
      { name: 'Central Library, IIT Madras', total_books: 300000, journals: 400, e_journals: 25000, digital_databases: 'IEEE, ACM, Springer, Elsevier, Scopus, Web of Science, MathSciNet', seating_capacity: 1200, timings: '24x7 reading hall access for students', services: 'Digital library, Reference, Reprography, Research support, Remote access to e-resources', description: 'Central library with extensive print and electronic collections and round-the-clock reading facilities.' },
    ],
    sports: [
      { sport_name: 'Cricket', category: 'Outdoor', facilities: 'Cricket ground and nets' },
      { sport_name: 'Football', category: 'Outdoor', facilities: 'Football ground' },
      { sport_name: 'Athletics', category: 'Outdoor', facilities: 'Athletics track' },
      { sport_name: 'Swimming', category: 'Aquatics', facilities: 'Swimming pool' },
      { sport_name: 'Tennis', category: 'Outdoor', courts_count: 4 },
      { sport_name: 'Basketball', category: 'Outdoor', courts_count: 4 },
      { sport_name: 'Indoor Sports Complex', category: 'Indoor', facilities: 'Badminton, table tennis, squash, gym' },
    ],
    infrastructure: [
      { name: 'IIT Madras Research Park', category: 'Research Centre', description: 'Large research and innovation park adjoining the campus, hosting R&D centres of multinational and Indian companies.' },
      { name: 'Incubation Cell / Startups', category: 'Research Centre', description: 'One of India\'s leading deep-technology incubation ecosystems.' },
      { name: 'Ocean Engineering laboratories', category: 'Laboratory', description: 'Wave basin and autonomous systems testing facilities.' },
      { name: 'Centre for Cybersecurity and Digital Forensics', category: 'Research Centre' },
      { name: 'Discoverability hub of classrooms and lecture halls', category: 'Digital Classroom', description: 'ICT-enabled lecture halls across academic departments.' },
    ],
    facilities: [
      { name: 'Campus-wide network and Wi-Fi', category: 'IT & Wi-Fi', available: 1 },
      { name: 'Hospital and 24x7 medical support', category: 'Medical', available: 1 },
      { name: 'Food courts, canteens and mess', category: 'Canteen & Food', available: 1 },
      { name: 'Bank branch and ATM', category: 'Bank & ATM', available: 1 },
      { name: 'Placement and career development cell', category: 'Placement Cell', available: 1 },
      { name: 'Student counselling and wellness centre', category: 'Counselling', available: 1, description: 'Wellness programmes including the PREM initiative for parents\' role in mentoring.' },
      { name: 'Innovation and entrepreneurship centre', category: 'Innovation / Incubation', available: 1 },
      { name: 'Campus security and emergency response', category: 'Security', available: 1 },
    ],
    scholarships: [
      { name: 'Merit-cum-Means Scholarship (Institute)', provider_type: 'College', category: 'Merit', amount_type: 'Part fee waiver', eligibility: 'Students with outstanding academic performance and family income within the prescribed limit.', is_active: 1 },
      { name: 'Free Studentship / full tuition waiver for eligible family income', provider_type: 'College', category: 'Need-based', amount_type: 'Full tuition waiver', eligibility: 'Students whose family income is below the threshold prescribed by the institute.' },
      { name: 'Government of India SC/ST/OBC scholarships', provider_type: 'Government', category: 'SC / ST', amount_type: 'Full tuition waiver', eligibility: 'As per central government scholarship schemes; applications through the National Scholarship Portal.' },
      { name: 'P M Vidyalaxmi education loan support', provider_type: 'Government', category: 'Need-based', amount_type: 'Full tuition waiver', eligibility: 'Loan support through the PM Vidyalaxmi portal for admitted students.' },
    ],
    events: [
      { title: 'Global Hyperloop Summit', category: 'Conference', start_date: '2026-09-21', venue: 'IIT Madras', status: 'Completed', description: 'Summit advancing high-speed and sustainable transport technologies.' },
      { title: '67th Institute Day', category: 'Other', start_date: '2026-07-15', venue: 'IIT Madras', status: 'Completed' },
      { title: '63rd Convocation', category: 'Other', start_date: '2026-08-01', venue: 'IIT Madras', status: 'Completed' },
      { title: 'Summer Fellowship 2026', category: 'Workshop', start_date: '2026-05-15', end_date: '2026-07-10', venue: 'IIT Madras', status: 'Completed' },
      { title: 'DDWS Innovation Challenge 2025-26', category: 'Technical', start_date: '2026-01-10', venue: 'IIT Madras', status: 'Completed', registration_link: 'https://www.iitm.ac.in/' },
      { title: 'Seminar — Spectrum Inspired Low-light Image Translation for Saliency Detection', category: 'Seminar', start_date: '2026-04-18', venue: 'IIT Madras', status: 'Completed' },
    ],
    achievements: [
      { title: 'No. 1 in India — NIRF ranking for nine consecutive years', category: 'Ranking', level: 'National', year: 2026, achieved_by: 'IIT Madras', award_organisation: 'Ministry of Education, NIRF' },
      { title: 'Ocean engineering students win Njord Autonomous Ship Challenge, Norway', category: 'Research', level: 'International', year: 2026, achieved_by: 'Students of the Department of Ocean Engineering', description: 'Team from IIT Madras won the Njord Autonomous Ship Challenge held in Norway.' },
      { title: 'Institute of Eminence status', category: 'Institutional', level: 'National', achieved_by: 'IIT Madras', award_organisation: 'Ministry of Education' },
    ],
    media: [
      { title: 'Global Hyperloop Summit at IIT Madras', type: 'Image', category: 'Event', url: 'https://www.iitm.ac.in/sites/default/files/styles/img_s5/public/happenings/press_release/pressrelease21_09_2026_12_12.jpg?itok=3rYMLOE5', is_cover: 1 },
      { title: 'Ocean engineering students win Njord Autonomous Ship Challenge', type: 'Image', category: 'Event', url: 'https://www.iitm.ac.in/sites/default/files/styles/img_s5/public/happenings/press_release/pressrelease21_09_2026_12_06.jpg?itok=43VtQRTh' },
      { title: 'Online BSc Programme', type: 'Image', category: 'Academic', url: 'https://www.iitm.ac.in/sites/default/files/card_images/homepagetile-onlineBscprogram.jpg' },
      { title: 'Exchange programmes', type: 'Image', category: 'Academic', url: 'https://www.iitm.ac.in/sites/default/files/card_images/homepagetile-exchange-program1_0_0.jpg' },
      { title: 'Joint degree programmes', type: 'Image', category: 'Academic', url: 'https://www.iitm.ac.in/sites/default/files/card_images/homepagetile-joint%20degree%20programme_0_0.jpg' },
      { title: 'International Masters Programme (I2MP)', type: 'Image', category: 'Academic', url: 'https://www.iitm.ac.in/sites/default/files/card_images/innovation4.png' },
    ],
    documents: [
      { title: 'UG programme admissions 2026', category: 'Admission Form', year: '2026', file_url: 'https://www.iitm.ac.in/sites/default/files/Others/UG_Admission_2026_updated.pdf' },
      { title: 'PG programme admissions 2026', category: 'Admission Form', year: '2026', file_url: 'https://www.iitm.ac.in/sites/default/files/Others/PG_Admissions_2026_updated.pdf' },
      { title: 'New academic programmes at IIT Madras 2026', category: 'Prospectus', year: '2026', file_url: 'https://www.iitm.ac.in/sites/default/files/Others/NEW-ACADEMIC-PROGRAMS-AT-IITMADRAS-2026-FINAL.docx' },
    ],
  },
];

/** Names used to generate realistic student applications/enquiries. */
export const STUDENT_NAMES = [
  'Aarav Krishnan', 'Divya Ramasamy', 'Harini Venkatesh', 'Karthik Subramanian', 'Meenakshi Iyer',
  'Nithin Raj', 'Pooja Lakshmi', 'Rahul Menon', 'Sneha Balaji', 'Vignesh Kumar',
  'Ananya Sharma', 'Arjun Nair', 'Bhavana Reddy', 'Deepak Chandran', 'Fathima Rahman',
  'Gokul Prasad', 'Ishwarya Sundar', 'Jeevan Anand', 'Keerthana Murugan', 'Lokesh Varma',
  'Monisha Devi', 'Naveen Bharathi', 'Oviya Selvam', 'Pranav Deshmukh', 'Rithika Jain',
  'Sandeep Yadav', 'Tanvi Gupta', 'Udhaya Sankar', 'Varun Pillai', 'Yamini Suresh',
  'Zoya Khan', 'Aravind Swamy', 'Charumathi Rajan', 'Dinesh Kannan', 'Ezhilarasi Pandian',
];

export const CITIES = [
  'Coimbatore', 'Chennai', 'Vellore', 'Madurai', 'Salem', 'Tiruchirappalli', 'Erode', 'Tirunelveli',
  'Bengaluru', 'Hyderabad', 'Kochi', 'Thiruvananthapuram', 'Vijayawada', 'Mysuru', 'Puducherry',
];

export const BOARDS = [
  'Tamil Nadu State Board (HSC)', 'CBSE (AISSCE)', 'ICSE / ISC', 'Kerala State Board',
  'Karnataka PU Board', 'Andhra Pradesh Board of Intermediate', 'Telangana Intermediate Board',
];

export const CATEGORIES = ['General', 'OBC', 'SC', 'ST', 'EWS', 'Minority'];
