import { createContext, useContext, useState, useEffect } from 'react'

const translations = {
  en: {
    // Common
    welcome: "Welcome",
    student: "Student",
    dashboard: "Dashboard",
    explore: "Explore Colleges",
    saved: "Saved",
    compare: "Compare",
    enquiries: "Enquiries",
    profile: "Profile",
    search: "Search",
    login: "Login",
    logout: "Logout",
    // Student Dashboard
    welcomeStudent: "Welcome, {name}! 👋",
    profileInfo: "Profile: {level} • {district} • Interested: {course} • {stream} • {percentage} • Hostel: {hostel} • Transport: {transport}",
    recentlyViewed: "Recently Viewed",
    recentlyViewedDesc: "Colleges you viewed",
    savedColleges: "Saved Colleges",
    savedCollegesDesc: "My saved list",
    compareList: "Compare List",
    compareListDesc: "For comparison",
    myEnquiries: "My Enquiries",
    myEnquiriesDesc: "With consent",
    recommendedForYou: "Recommended for You",
    basedOn: "Based on {course}",
    whyShown: "Why shown: Matches your selected {course}, {district}, {type} type, {level} level",
    viewAll: "View All →",
    recentlyViewedColleges: "Recently Viewed Colleges",
    clearHistory: "Clear History",
    view: "View",
    remove: "Remove",
    noSaved: "No saved colleges yet",
    saveHint: "Save colleges to see here - activity tracked securely",
    viewAllSaved: "View All Saved",
    yourActivity: "Your Activity - Securely Tracked",
    collegeViews: "College Views",
    courseViews: "Course Views",
    savedActivity: "Saved",
    enquiriesConsent: "Enquiries (with consent)",
    privacyNote: "🔒 Privacy: Your personal info NOT automatically shared to colleges when you view. Only when you click ENQUIRE NOW with consent, info shared. Activity tracked securely for recommendations.",
    navigation: "Navigation",
    exploreCollegesNav: "Explore Colleges",
    coursesNav: "Courses",
    compareNav: "Compare",
    myEnquiriesNav: "My Enquiries",
    searchColleges: "Search Colleges",
    filters: "Filters",
    district: "District",
    course: "Course",
    collegeType: "College Type",
    save: "Save",
    compareBtn: "Compare",
    viewDetails: "View Details",
    verified: "Verified",
    placement: "Placement",
    language: "Language",
    english: "English",
    tamil: "தமிழ்",
    tamilEnglishToggle: "தமிழ் / English",
    profileComplete: "Profile 100% Complete",
    topCollegesForYou: "Top Colleges for Your {percentage}%",
    originalDocs: "Original Documents",
    autoPercentage: "Auto Percentage",
    dreamCourse: "Dream Course - What you want to study",
    homeTitle: "Discover Your Dream College in Tamil Nadu",
    homeSubtitle: "Across all districts - Premium trusted platform",
    allDistricts: "All Districts - TN",
    home: "Home",
    courses: "Courses",
    // Student Details Proper - Full
    studentDetails: "Student Details",
    basicInfo: "Basic Information",
    personalFamily: "Personal & Family Details",
    educationDocs: "Education & Documents",
    preferencesTopColleges: "Preferences & Top Colleges",
    fullName: "Full Name",
    fullNameTa: "முழு பெயர்",
    email: "Email",
    mobile: "Mobile Number",
    alternateMobile: "Alternate Mobile",
    password: "Password",
    dob: "Date of Birth",
    gender: "Gender",
    bloodGroup: "Blood Group",
    nationality: "Nationality",
    religion: "Religion",
    community: "Community",
    caste: "Caste",
    aadharNumber: "Aadhar Number",
    fatherName: "Father Name",
    motherName: "Mother Name",
    fatherOccupation: "Father Occupation",
    motherOccupation: "Mother Occupation",
    parentMobile: "Parent Mobile",
    annualIncome: "Annual Family Income",
    permanentAddress: "Permanent Address",
    pincode: "Pincode",
    state: "State",
    city: "City",
    educationLevel: "Education Level",
    schoolCollege: "School / College",
    board: "Board / University",
    yearOfPassing: "Year of Passing",
    marksObtained: "Marks Obtained",
    totalMarks: "Total Marks",
    percentage: "Percentage",
    grade: "Grade",
    cutoff: "Cutoff",
    groupStream: "Group / Stream",
    medium: "Medium",
    interestedCourse: "Interested Course - What you want to study",
    interestedSubject: "Interested Subject",
    careerGoal: "Career Goal - What you want to become",
    whyThisCourse: "Why This Course",
    preferredDistrict: "Preferred District",
    budgetRange: "Budget Range",
    scholarshipNeeded: "Scholarship Needed",
    hostelRequired: "Hostel Required",
    transportRequired: "Transport Required",
    documents: "Documents",
    tenthMarksheet: "10th Mark Sheet",
    twelfthMarksheet: "12th Mark Sheet",
    tc: "Transfer Certificate (TC)",
    communityCertificate: "Community Certificate",
    incomeCertificate: "Income Certificate",
    aadharCard: "Aadhar Card",
    photo: "Passport Size Photo",
    nativityCertificate: "Nativity Certificate",
    firstGraduateCertificate: "First Graduate Certificate",
    specialReservation: "Special Reservation Certificate",
    documentsUploaded: "Documents Uploaded",
    marksAuto: "Marks - Auto Percentage - Automatic calculation",
    topRatedColleges: "Top Rated Colleges",
    eligibilityMatch: "Eligibility Match",
    matchPercent: "Match Percent",
    placementPercent: "Placement Percent",
    accreditation: "Accreditation",
    reason: "Reason",
    whyTheseColleges: "Why These Colleges",
    reviewDetails: "Review Your Details",
    studentId: "Student ID",
    nameAsPerAadhar: "Name as per Aadhar",
    dreamCourseLabel: "Dream Course - Enna Padikka Aasa Padra",
    originalDocsSubmit: "Original Documents - Submit Pantra Mathiri",
    fullInfo: "Full Information - Vera enna info venumoo atha",
    autoPercentResult: "Auto Calculation Result",
    topCollegesForPercent: "Top Colleges for {percent}% - {course}",
    secureDocs: "All documents are securely stored",
    privacyPromise: "Privacy Promise - Original Documents Secure",
    // Profile page
    myProfile: "My Profile",
    editProfile: "Edit Profile",
    personalInfo: "Personal Information",
    familyInfo: "Family Information",
    educationInfo: "Education Information",
    contactInfo: "Contact Information",
    addressInfo: "Address Information",
    // Additional
    asPerAadhar: "As per Aadhar",
    required: "Required",
    optional: "Optional",
    yes: "Yes",
    no: "No",
    male: "Male",
    female: "Female",
    other: "Other",
    outstanding: "Outstanding",
    excellent: "Excellent",
    veryGood: "Very Good",
    good: "Good",
    average: "Average",
    pass: "Pass",
    // Dashboard detailed
    myDetails: "My Details - Proper",
    viewProfile: "View Full Profile",
    myDocuments: "My Documents",
    myMarks: "My Marks & Percentage",
    myPreferences: "My Preferences",
    myTopColleges: "My Top Colleges Based on Percentage",
    // For proper display
    labelFullName: "Full Name (As per Aadhar)",
    labelEmail: "Email Address",
    labelMobile: "Mobile Number",
    labelDob: "Date of Birth",
    labelGender: "Gender",
    labelCommunity: "Community",
    labelAadhar: "Aadhar Number",
    labelFather: "Father Name",
    labelMother: "Mother Name",
    labelIncome: "Annual Income",
    labelAddress: "Permanent Address",
    labelEducation: "Education Level",
    labelSchool: "School / College Name",
    labelMarks: "Marks Obtained / Total",
    labelPercentage: "Percentage & Grade",
    labelCourse: "Interested Course",
    labelDistrict: "District & City",
    labelHostel: "Hostel & Transport",
    // Toggle proper
    properDetailsTamilEnglish: "Proper Student Details in Tamil / English - Toggle-la Maarum",
    detailsInTamil: "Details in Tamil",
    detailsInEnglish: "Details in English"
  },
  ta: {
    welcome: "வரவேற்கிறோம்",
    student: "மாணவர்",
    dashboard: "டாஷ்போர்டு",
    explore: "கல்லூரிகளை ஆராயுங்கள்",
    saved: "சேமித்தவை",
    compare: "ஒப்பிடுக",
    enquiries: "விசாரணைகள்",
    profile: "சுயவிவரம்",
    search: "தேடு",
    login: "உள்நுழை",
    logout: "வெளியேறு",
    welcomeStudent: "வரவேற்கிறோம், {name}! 👋",
    profileInfo: "சுயவிவரம்: {level} • {district} • ஆர்வம்: {course} • {stream} • {percentage} • விடுதி: {hostel} • போக்குவரத்து: {transport}",
    recentlyViewed: "சமீபத்தில் பார்த்தவை",
    recentlyViewedDesc: "நீங்கள் பார்த்த கல்லூரிகள்",
    savedColleges: "சேமித்த கல்லூரிகள்",
    savedCollegesDesc: "எனது சேமிப்பு பட்டியல்",
    compareList: "ஒப்பீட்டு பட்டியல்",
    compareListDesc: "ஒப்பிடுவதற்கு",
    myEnquiries: "எனது விசாரணைகள்",
    myEnquiriesDesc: "ஒப்புதலுடன்",
    recommendedForYou: "உங்களுக்கு பரிந்துரைக்கப்பட்டவை",
    basedOn: "{course} அடிப்படையில்",
    whyShown: "ஏன் காட்டப்பட்டது: நீங்கள் தேர்ந்தெடுத்த {course}, {district}, {type} வகை, {level} நிலைக்கு பொருந்துகிறது",
    viewAll: "அனைத்தையும் பார் →",
    recentlyViewedColleges: "சமீபத்தில் பார்த்த கல்லூரிகள்",
    clearHistory: "வரலாற்றை அழி",
    view: "பார்",
    remove: "நீக்கு",
    noSaved: "இன்னும் சேமிக்கப்பட்ட கல்லூரிகள் இல்லை",
    saveHint: "இங்கே பார்க்க கல்லூரிகளை சேமிக்கவும் - செயல்பாடு பாதுகாப்பாக கண்காணிக்கப்படுகிறது",
    viewAllSaved: "சேமித்த அனைத்தையும் பார்",
    yourActivity: "உங்கள் செயல்பாடு - பாதுகாப்பாக கண்காணிக்கப்படுகிறது",
    collegeViews: "கல்லூரி பார்வைகள்",
    courseViews: "பாட பார்வைகள்",
    savedActivity: "சேமித்தவை",
    enquiriesConsent: "விசாரணைகள் (ஒப்புதலுடன்)",
    privacyNote: "🔒 தனியுரிமை: நீங்கள் பார்க்கும்போது உங்கள் தனிப்பட்ட தகவல் கல்லூரிகளுக்கு தானாக பகிரப்படாது. நீங்கள் ஒப்புதலுடன் ENQUIRE NOW கிளிக் செய்யும்போது மட்டுமே தகவல் பகிரப்படும்.",
    navigation: "வழிசெலுத்தல்",
    exploreCollegesNav: "கல்லூரிகளை ஆராயுங்கள்",
    coursesNav: "பாடங்கள்",
    compareNav: "ஒப்பிடுக",
    myEnquiriesNav: "எனது விசாரணைகள்",
    searchColleges: "கல்லூரிகளை தேடுங்கள்",
    filters: "வடிகட்டிகள்",
    district: "மாவட்டம்",
    course: "பாடம்",
    collegeType: "கல்லூரி வகை",
    save: "சேமி",
    compareBtn: "ஒப்பிடு",
    viewDetails: "விவரங்களை பார்",
    verified: "சரிபார்க்கப்பட்டது",
    placement: "வேலைவாய்ப்பு",
    language: "மொழி",
    english: "English",
    tamil: "தமிழ்",
    tamilEnglishToggle: "தமிழ் / English",
    profileComplete: "சுயவிவரம் 100% முடிந்தது",
    topCollegesForYou: "உங்கள் {percentage}% க்கான சிறந்த கல்லூரிகள்",
    originalDocs: "அசல் ஆவணங்கள்",
    autoPercentage: "தானியங்கி சதவீதம்",
    dreamCourse: "கனவு பாடம் - நீங்கள் என்ன படிக்க விரும்புகிறீர்கள்",
    homeTitle: "தமிழ்நாட்டில் உங்கள் கனவு கல்லூரியை கண்டறியுங்கள்",
    homeSubtitle: "அனைத்து மாவட்டங்களிலும் - பிரீமியம் நம்பகமான தளம்",
    allDistricts: "அனைத்து மாவட்டங்களும் - தமிழ்நாடு",
    home: "முகப்பு",
    courses: "பாடங்கள்",
    // Student Details Proper - Tamil Full
    studentDetails: "மாணவர் விவரங்கள்",
    basicInfo: "அடிப்படை தகவல்",
    personalFamily: "தனிப்பட்ட & குடும்ப விவரங்கள்",
    educationDocs: "கல்வி & ஆவணங்கள்",
    preferencesTopColleges: "விருப்பங்கள் & சிறந்த கல்லூரிகள்",
    fullName: "முழு பெயர்",
    fullNameTa: "முழு பெயர்",
    email: "மின்னஞ்சல்",
    mobile: "கைபேசி எண்",
    alternateMobile: "மாற்று கைபேசி",
    password: "கடவுச்சொல்",
    dob: "பிறந்த தேதி",
    gender: "பாலினம்",
    bloodGroup: "இரத்த வகை",
    nationality: "தேசியம்",
    religion: "மதம்",
    community: "சமூகம்",
    caste: "சாதி",
    aadharNumber: "ஆதார் எண்",
    fatherName: "தந்தை பெயர்",
    motherName: "தாய் பெயர்",
    fatherOccupation: "தந்தை தொழில்",
    motherOccupation: "தாய் தொழில்",
    parentMobile: "பெற்றோர் கைபேசி",
    annualIncome: "ஆண்டு குடும்ப வருமானம்",
    permanentAddress: "நிரந்தர முகவரி",
    pincode: "அஞ்சல் குறியீடு",
    state: "மாநிலம்",
    city: "நகரம்",
    educationLevel: "கல்வி நிலை",
    schoolCollege: "பள்ளி / கல்லூரி",
    board: "வாரியம் / பல்கலைக்கழகம்",
    yearOfPassing: "தேர்ச்சி ஆண்டு",
    marksObtained: "பெற்ற மதிப்பெண்கள்",
    totalMarks: "மொத்த மதிப்பெண்கள்",
    percentage: "சதவீதம்",
    grade: "தரம்",
    cutoff: "கட்-ஆஃப்",
    groupStream: "குழு / பிரிவு",
    medium: "பயிற்று மொழி",
    interestedCourse: "ஆர்வமுள்ள பாடம் - நீங்கள் என்ன படிக்க விரும்புகிறீர்கள்",
    interestedSubject: "ஆர்வமுள்ள பாடம்",
    careerGoal: "தொழில் இலக்கு - நீங்கள் என்ன ஆக விரும்புகிறீர்கள்",
    whyThisCourse: "ஏன் இந்த பாடம்",
    preferredDistrict: "விருப்ப மாவட்டம்",
    budgetRange: "பட்ஜெட் வரம்பு",
    scholarshipNeeded: "உதவித்தொகை தேவையா",
    hostelRequired: "விடுதி தேவையா",
    transportRequired: "போக்குவரத்து தேவையா",
    documents: "ஆவணங்கள்",
    tenthMarksheet: "10ம் வகுப்பு மதிப்பெண் பட்டியல்",
    twelfthMarksheet: "12ம் வகுப்பு மதிப்பெண் பட்டியல்",
    tc: "மாற்று சான்றிதழ் (TC)",
    communityCertificate: "சமூக சான்றிதழ்",
    incomeCertificate: "வருமான சான்றிதழ்",
    aadharCard: "ஆதார் அட்டை",
    photo: "பாஸ்போர்ட் அளவு புகைப்படம்",
    nativityCertificate: "பூர்வீக சான்றிதழ்",
    firstGraduateCertificate: "முதல் பட்டதாரி சான்றிதழ்",
    specialReservation: "சிறப்பு இடஒதுக்கீடு சான்றிதழ்",
    documentsUploaded: "பதிவேற்றப்பட்ட ஆவணங்கள்",
    marksAuto: "மதிப்பெண்கள் - தானியங்கி சதவீதம் - தானியங்கி கணக்கீடு",
    topRatedColleges: "சிறந்த தரமதிப்பீடு கல்லூரிகள்",
    eligibilityMatch: "தகுதி பொருத்தம்",
    matchPercent: "பொருத்த சதவீதம்",
    placementPercent: "வேலைவாய்ப்பு சதவீதம்",
    accreditation: "அங்கீகாரம்",
    reason: "காரணம்",
    whyTheseColleges: "ஏன் இந்த கல்லூரிகள்",
    reviewDetails: "உங்கள் விவரங்களை சரிபார்க்கவும்",
    studentId: "மாணவர் ID",
    nameAsPerAadhar: "ஆதார் படி பெயர்",
    dreamCourseLabel: "கனவு பாடம் - என்ன படிக்க ஆசைப்படுகிறாய்",
    originalDocsSubmit: "அசல் ஆவணங்கள் - சமர்ப்பிக்கும் மாதிரி",
    fullInfo: "முழு தகவல் - வேறு என்ன தகவல் வேண்டுமோ அது",
    autoPercentResult: "தானியங்கி கணக்கீடு முடிவு",
    topCollegesForPercent: "{percent}% க்கான சிறந்த கல்லூரிகள் - {course}",
    secureDocs: "அனைத்து ஆவணங்களும் பாதுகாப்பாக சேமிக்கப்படுகின்றன",
    privacyPromise: "தனியுரிமை வாக்குறுதி - அசல் ஆவணங்கள் பாதுகாப்பு",
    myProfile: "எனது சுயவிவரம்",
    editProfile: "சுயவிவரத்தை திருத்து",
    personalInfo: "தனிப்பட்ட தகவல்",
    familyInfo: "குடும்ப தகவல்",
    educationInfo: "கல்வி தகவல்",
    contactInfo: "தொடர்பு தகவல்",
    addressInfo: "முகவரி தகவல்",
    asPerAadhar: "ஆதார் படி",
    required: "தேவையானது",
    optional: "விருப்பமானது",
    yes: "ஆம்",
    no: "இல்லை",
    male: "ஆண்",
    female: "பெண்",
    other: "மற்றவை",
    outstanding: "சிறப்பானது",
    excellent: "சிறந்தது",
    veryGood: "மிக நல்லது",
    good: "நல்லது",
    average: "சராசரி",
    pass: "தேர்ச்சி",
    myDetails: "எனது விவரங்கள் - முழுமையானது",
    viewProfile: "முழு சுயவிவரத்தை பார்",
    myDocuments: "எனது ஆவணங்கள்",
    myMarks: "எனது மதிப்பெண்கள் & சதவீதம்",
    myPreferences: "எனது விருப்பங்கள்",
    myTopColleges: "எனது சதவீதத்தின் அடிப்படையில் சிறந்த கல்லூரிகள்",
    labelFullName: "முழு பெயர் (ஆதார் படி)",
    labelEmail: "மின்னஞ்சல் முகவரி",
    labelMobile: "கைபேசி எண்",
    labelDob: "பிறந்த தேதி",
    labelGender: "பாலினம்",
    labelCommunity: "சமூகம்",
    labelAadhar: "ஆதார் எண்",
    labelFather: "தந்தை பெயர்",
    labelMother: "தாய் பெயர்",
    labelIncome: "ஆண்டு வருமானம்",
    labelAddress: "நிரந்தர முகவரி",
    labelEducation: "கல்வி நிலை",
    labelSchool: "பள்ளி / கல்லூரி பெயர்",
    labelMarks: "பெற்ற / மொத்த மதிப்பெண்கள்",
    labelPercentage: "சதவீதம் & தரம்",
    labelCourse: "ஆர்வமுள்ள பாடம்",
    labelDistrict: "மாவட்டம் & நகரம்",
    labelHostel: "விடுதி & போக்குவரத்து",
    properDetailsTamilEnglish: "தமிழ் / English இல் முழுமையான மாணவர் விவரங்கள் - Toggle-ல் மாறும்",
    detailsInTamil: "தமிழில் விவரங்கள்",
    detailsInEnglish: "ஆங்கிலத்தில் விவரங்கள்"
  }
}

const LanguageContext = createContext()

export function LanguageProvider({ children }) {
  const [language, setLanguageState] = useState(() => {
    try {
      return localStorage.getItem('tn_student_language') || 'en'
    } catch {
      return 'en'
    }
  })

  const setLanguage = (lang) => {
    setLanguageState(lang)
    try {
      localStorage.setItem('tn_student_language', lang)
    } catch {}
  }

  const t = (key, params = {}) => {
    const langPack = translations[language] || translations.en
    let text = langPack[key] || translations.en[key] || key
    Object.entries(params).forEach(([k, v]) => {
      text = text.replace(`{${k}}`, v)
    })
    return text
  }

  const [isStudent, setIsStudent] = useState(false)
  const [isStudentPage, setIsStudentPage] = useState(false)
  useEffect(() => {
    const checkStudent = () => {
      try {
        const s = localStorage.getItem('tn_current_student')
        setIsStudent(!!s)
        const path = window.location.pathname
        setIsStudentPage(path.startsWith('/student') || path.includes('student'))
      } catch {
        setIsStudent(false)
      }
    }
    checkStudent()
    window.addEventListener('storage', checkStudent)
    const interval = setInterval(checkStudent, 1000)
    return () => {
      window.removeEventListener('storage', checkStudent)
      clearInterval(interval)
    }
  }, [])

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, isStudent, isStudentPage, translations }}>
      {children}
    </LanguageContext.Provider>
  )
}

export function useLanguage() {
  const ctx = useContext(LanguageContext)
  if (!ctx) throw new Error('useLanguage must be used within LanguageProvider')
  return ctx
}
